/* 데일리스코어 부상자 정보 데이터
 * 모든 항목은 구단 공식 발표 및 현지 언론 보도를 확인한 뒤 자체적으로 요약/재작성한 내용입니다.
 * 특정 사이트의 문장을 그대로 옮기지 않고, 확인된 사실(팩트)만 반영해 새로 작성합니다.
 * status: "out"(결장 확정) | "doubtful"(출전 불투명) | "questionable"(출전 여부 미정) | "ok"(복귀/훈련 합류)
 */
export type InjuryStatus = "out" | "doubtful" | "questionable" | "ok";

export interface InjuryItem {
  id: string;
  photoQuery?: string;
  teamEn?: string;
  league: string;
  leagueLabel: string;
  team: string;
  player: string;
  status: InjuryStatus;
  updated: string;
  headline: string;
  summary: string;
}

export const INJURY_STATUS_LABEL: Record<InjuryStatus, string> = {
  out: "결장",
  doubtful: "출전 불투명",
  questionable: "출전 미정",
  ok: "복귀",
};

export const INJURIES: InjuryItem[] = [
  {
    id: "mlb-judge-rib",
    photoQuery: "Aaron Judge",
    teamEn: "New York Yankees",
    league: "mlb",
    leagueLabel: "MLB",
    team: "뉴욕 양키스",
    player: "애런 저지",
    status: "doubtful",
    updated: "2026-08-20",
    headline: "저지, 갈비뼈 피로골절로 재활 중… 이번 주 타격 훈련 돌입",
    summary:
      "갈비뼈 피로골절로 이탈했던 저지가 수영장에서 스윙 관련 재활 훈련을 이어가고 있으며, 8월 17일이 속한 주부터 본격적인 타격 훈련 단계에 들어갈 예정이에요. 실전 복귀까지는 좀 더 시간이 필요할 것으로 보여요.",
  },
  {
    id: "mlb-fried-elbow",
    photoQuery: "Max Fried",
    teamEn: "New York Yankees",
    league: "mlb",
    leagueLabel: "MLB",
    team: "뉴욕 양키스",
    player: "맥스 프리드",
    status: "doubtful",
    updated: "2026-08-22",
    headline: "프리드, 사이드 세션 소화… 라이브 배팅 훈련 앞둬",
    summary:
      "좌측 팔꿈치 골타박상으로 이탈했던 프리드가 8월 22일 사이드 세션을 소화하며 재활에 속도를 냈어요. 결과에 따라 라이브 배팅 훈련 단계로 넘어갈 수 있어, 최소 이탈 기간인 15일 내 로테이션 복귀 가능성도 남아 있어요.",
  },
  {
    id: "mlb-marte-knee",
    photoQuery: "Ketel Marte",
    teamEn: "Arizona Diamondbacks",
    league: "mlb",
    leagueLabel: "MLB",
    team: "애리조나 다이아몬드백스",
    player: "케텔 마르테",
    status: "out",
    updated: "2026-08-20",
    headline: "마르테, 좌측 무릎 염증으로 부상자 명단 등재",
    summary:
      "다이아몬드백스가 8월 20일 밤 케텔 마르테를 좌측 무릎 염증을 이유로 부상자 명단에 올렸어요. 팀 내야진 운용에 변화가 예상돼요.",
  },
  {
    id: "mlb-abrams-ankle",
    photoQuery: "CJ Abrams",
    teamEn: "Washington Nationals",
    league: "mlb",
    leagueLabel: "MLB",
    team: "워싱턴 내셔널스",
    player: "CJ 에이브럼스",
    status: "questionable",
    updated: "2026-08-20",
    headline: "에이브럼스, 발목 염좌로 레인저스전 결장",
    summary:
      "에이브럼스가 8월 19일 경기 막판 발목을 접질렀고, 다음 날 레인저스전에는 결장했어요. 명단 등재 여부는 아직 확정되지 않았어요.",
  },
  {
    id: "mlb-garcia-hamstring",
    photoQuery: "Maikel Garcia",
    teamEn: "Kansas City Royals",
    league: "mlb",
    leagueLabel: "MLB",
    team: "캔자스시티 로열스",
    player: "마이켈 가르시아",
    status: "out",
    updated: "2026-08-20",
    headline: "가르시아, 햄스트링 부상으로 IL 등재 예정",
    summary:
      "쿼트라로 감독이 마이켈 가르시아가 햄스트링 부상으로 부상자 명단에 오를 예정이라고 밝혔어요. 정확한 결장 기간은 추가 검진 후 나올 전망이에요.",
  },
  {
    id: "epl-arsenal-saliba-timber",
    photoQuery: "William Saliba",
    teamEn: "Arsenal",
    league: "epl",
    leagueLabel: "EPL",
    team: "아스널",
    player: "살리바 · 티머버",
    status: "out",
    updated: "2026-08-21",
    headline: "아스널, 개막전서 살리바·티머버 결장",
    summary:
      "아스널이 프리미어리그 개막전을 앞두고 윌리안 살리바와 야프 티머버 없이 나서요. 다만 데클런 라이스와 부카요 사카는 출전 명단에 포함될 예정이에요.",
  },
  {
    id: "epl-mancity-doku",
    photoQuery: "Jeremy Doku",
    teamEn: "Manchester City",
    league: "epl",
    leagueLabel: "EPL",
    team: "맨체스터 시티",
    player: "제레미 도쿠",
    status: "doubtful",
    updated: "2026-08-21",
    headline: "도쿠, 커뮤니티 실드서 종아리 부상… 개막전 결장 위기",
    summary:
      "제레미 도쿠가 커뮤니티 실드 경기 중 종아리를 다쳤어요. 맨시티의 이번 주말 결장 명단에 이름을 올린 유일한 선수예요.",
  },
  {
    id: "epl-manutd-ugarte-deligt",
    photoQuery: "Manuel Ugarte",
    teamEn: "Manchester United",
    league: "epl",
    leagueLabel: "EPL",
    team: "맨체스터 유나이티드",
    player: "우가르테 · 더 리흐트",
    status: "out",
    updated: "2026-08-21",
    headline: "맨유, 우가르테 장기 이탈… 더 리흐트도 컨디션 난조",
    summary:
      "마누엘 우가르테가 무릎 부상으로 장기간 결장이 예상돼요. 마타이스 더 리흐트도 허리 통증으로 아직 출전 가능 상태가 아니에요.",
  },
  {
    id: "epl-spurs-porro-vandeven",
    photoQuery: "Pedro Porro",
    teamEn: "Tottenham",
    league: "epl",
    leagueLabel: "EPL",
    team: "토트넘 홋스퍼",
    player: "포로 · 반 더 벤",
    status: "out",
    updated: "2026-08-21",
    headline: "토트넘, 포로·반 더 벤 결장… 나머지 자원은 정상 가동",
    summary:
      "페드로 포로와 미키 반 더 벤이 이번 경기 명단에서 빠져요. 대신 솔란케, 우도지, 매디슨, 페르난데스는 정상적으로 출전 가능한 상태예요.",
  },
  {
    id: "laliga-realmadrid-rodrygo",
    photoQuery: "Rodrygo",
    teamEn: "Real Madrid",
    league: "laliga",
    leagueLabel: "라리가",
    team: "레알 마드리드",
    player: "호드리구",
    status: "out",
    updated: "2026-08-20",
    headline: "호드리구, 무릎 중상으로 2027년 초 복귀 목표",
    summary:
      "호드리구가 올 시즌 초 심각한 무릎 부상을 당해 2027년 초반이 되어야 그라운드에 복귀할 수 있을 것으로 보여요. 팀은 장기 공백에 대비한 공격진 운용을 준비하고 있어요.",
  },
  {
    id: "laliga-realmadrid-militao-mendy",
    photoQuery: "Eder Militao",
    teamEn: "Real Madrid",
    league: "laliga",
    leagueLabel: "라리가",
    team: "레알 마드리드",
    player: "미리타오 · 멘디",
    status: "out",
    updated: "2026-08-20",
    headline: "레알 마드리드 수비진 연쇄 이탈… 미리타오·멘디 모두 결장",
    summary:
      "에데르 미리타오가 햄스트링 수술 후 최소 한 달가량 결장이 예상되고, 페를랑 멘디도 허벅지 부상으로 상당 기간 빠질 전망이에요. 시즌 초반 수비 로테이션에 부담이 커졌어요.",
  },
  {
    id: "ligue1-monaco-pogba",
    photoQuery: "Paul Pogba",
    teamEn: "Monaco",
    league: "ligue1",
    leagueLabel: "리그앙",
    team: "AS 모나코",
    player: "폴 포그바",
    status: "out",
    updated: "2026-08-21",
    headline: "포그바, 새 허벅지 부상 끝에 모나코와 계약 해지",
    summary:
      "폴 포그바가 훈련 중 왼쪽 허벅지를 다시 다치며 쓰러졌고, 모나코 구단은 결국 그와의 계약을 해지하기로 했어요. 지난 시즌 출전 기회가 극히 적었던 포그바는 이번 부상을 끝으로 클럽을 떠나게 됐어요.",
  },
  {
    id: "ligue1-angers-belkebla",
    photoQuery: "Haris Belkebla",
    teamEn: "Angers",
    league: "ligue1",
    leagueLabel: "리그앙",
    team: "앙제",
    player: "하리스 벨케블라",
    status: "out",
    updated: "2026-08-19",
    headline: "벨케블라, 허벅지 부상 수술… 약 한 달 결장",
    summary:
      "앙제의 하리스 벨케블라가 허벅지 부상으로 수술을 받았고, 회복까지 약 한 달 정도가 소요될 것으로 예상돼요.",
  },
  {
    id: "mlb-soderstrom-hip",
    photoQuery: "Tyler Soderstrom",
    teamEn: "Athletics",
    league: "mlb",
    leagueLabel: "MLB",
    team: "오클랜드 애슬레틱스",
    player: "타일러 소더스트롬",
    status: "out",
    updated: "2026-08-21",
    headline: "소더스트롬, 왼쪽 고관절 수술로 시즌 아웃",
    summary:
      "애슬레틱스 외야수 타일러 소더스트롬이 왼쪽 고관절 임핀지먼트로 결국 시즌을 마감하는 수술을 받기로 했어요. 여름 동안 같은 부위로 두 차례나 부상자 명단에 올랐던 끝에 전문의 상담 후 내려진 결정이에요.",
  },
  {
    id: "mlb-wilson-shoulder",
    photoQuery: "Jacob Wilson",
    teamEn: "Athletics",
    league: "mlb",
    leagueLabel: "MLB",
    team: "오클랜드 애슬레틱스",
    player: "제이컵 윌슨",
    status: "out",
    updated: "2026-08-22",
    headline: "윌슨, 시즌 아웃 공식 확정… 새크라멘토서 전문의 상담",
    summary:
      "애슬레틱스가 제이컵 윌슨의 남은 시즌 결장을 공식 확정했어요. 지난 5월 다이빙 캐치 도중 탈구됐던 왼쪽 어깨가 재활에도 반응하지 않으면서, 윌슨은 새크라멘토로 이동해 전문의 진단을 받을 예정이에요.",
  },
  {
    id: "epl-brighton-minteh",
    photoQuery: "Yankuba Minteh",
    teamEn: "Brighton",
    league: "epl",
    leagueLabel: "EPL",
    team: "브라이튼",
    player: "얀쿠바 민테",
    status: "out",
    updated: "2026-08-21",
    headline: "민테, 다리 수술 받아… 복귀까지 두 달 이상",
    summary:
      "브라이튼의 얀쿠바 민테가 다리 부상으로 수술을 받았고, 복귀까지 두 달 이상 걸릴 것으로 예상돼요. 시즌 개막을 앞두고 팀 공격진에 공백이 생겼어요.",
  },
  {
    id: "epl-brighton-baleba",
    photoQuery: "Carlos Baleba",
    teamEn: "Brighton",
    league: "epl",
    leagueLabel: "EPL",
    team: "브라이튼",
    player: "카를로스 발레바",
    status: "doubtful",
    updated: "2026-08-21",
    headline: "발레바, 발목 인대 부상으로 개막전 결장 위기",
    summary:
      "카를로스 발레바가 발목 인대 부상을 안고 있어 시즌 개막전 출전이 불투명해요. 민테의 이탈까지 겹치며 브라이튼은 개막을 앞두고 전력 손실을 걱정하고 있어요.",
  },
  {
    id: "bundesliga-muslija-acl",
    photoQuery: "Florent Muslija",
    league: "bundesliga",
    leagueLabel: "분데스리가",
    team: "소속팀 확인 중",
    player: "플로렌트 무슬리야",
    status: "out",
    updated: "2026-08-18",
    headline: "무슬리야, 십자인대 부상에서 회복 중… 10월 복귀 목표",
    summary:
      "십자인대 부상으로 이탈했던 무슬리야의 복귀 예상 시점은 10월 10일이에요. 분데스리가 여러 팀에서 8월 하순 복귀를 목표로 하는 선수들도 함께 관찰되고 있어요.",
  },
  {
    id: "epl-astonvilla-gomes-madjo",
    photoQuery: "Joao Gomes",
    teamEn: "Aston Villa",
    league: "epl",
    leagueLabel: "EPL",
    team: "애스턴 빌라",
    player: "조앙 고메스 · 브라이언 마조",
    status: "out",
    updated: "2026-08-21",
    headline: "애스턴 빌라, 고메스·마조 동시 이탈… 개막전 비상",
    summary:
      "울버햄튼에서 이적한 조앙 고메스가 PSG와의 UEFA 슈퍼컵 데뷔전에서 종아리를 다쳐 2~4주가량 결장이 예상돼요. 같은 경기에서 데뷔골을 넣었던 브라이언 마조도 부상을 안고 9월에나 복귀가 가능할 전망이라, 8월 23일 브라이튼전을 앞둔 에메리 감독의 고민이 깊어졌어요.",
  },
  {
    id: "mlb-story-hernia",
    photoQuery: "Trevor Story",
    teamEn: "Boston Red Sox",
    league: "mlb",
    leagueLabel: "MLB",
    team: "보스턴 레드삭스",
    player: "트레버 스토리",
    status: "questionable",
    updated: "2026-08-21",
    headline: "스토리, 서혼 재활 순항 중… 이번 주말 복귀 저울질",
    summary:
      "5월 서혼 수술 후 60일 부상자 명단에 있던 스토리가 트리플A 우스터에서 재활 경기를 이어가고 있어요. 8월 21일 활성화는 불발됐지만 화요일과 수요일 시러큐스 원정 경기를 더 치른 뒤 구단과 최종 재평가를 거쳐 이번 주말 자이언츠전 복귀 여부가 결정될 예정이에요.",
  },
  {
    id: "mlb-chapman-core-surgery",
    photoQuery: "Matt Chapman",
    teamEn: "San Francisco Giants",
    league: "mlb",
    leagueLabel: "MLB",
    team: "샌프란시스코 자이언츠",
    player: "맷 채프먼",
    status: "out",
    updated: "2026-08-22",
    headline: "채프먼, 복부 근육 봉합 수술 받아… 시즌 조기 마감",
    summary:
      "샌프란시스코 3루수 맷 채프먼이 필라델피아에서 복부 코어 근육 봉합 수술을 받으며 남은 시즌을 모두 접었어요. 4월 신시내티 원정 중 다친 부위를 통증을 참고 버티다 7월 1일 부상자 명단에 올랐고, 재활에는 8~12주가 걸릴 전망이라 2027시즌 정상 복귀를 목표로 하고 있어요.",
  },
  {
    id: "mlb-pena-hand-contusion",
    photoQuery: "Jeremy Pena",
    teamEn: "Houston Astros",
    league: "mlb",
    leagueLabel: "MLB",
    team: "휴스턴 애스트로스",
    player: "제레미 페냐",
    status: "questionable",
    updated: "2026-08-22",
    headline: "페냐, 손 타박상 X레이·MRI 모두 이상 없음… 데이 투 데이",
    summary:
      "제레미 페냐가 8월 19일 에인절스전에서 시속 100마일 싱커에 오른손을 맞고 경기 중 교체됐어요. X레이와 MRI 모두 구조적 손상은 없었지만 부기와 통증이 남아 있어 구단은 그를 데이 투 데이로 분류하고 부상자 명단행은 피할 수 있길 기대하고 있어요.",
  },
  {
    id: "ligue1-auxerre-diousse-acl",
    photoQuery: "Assane Dioussé",
    teamEn: "Auxerre",
    league: "ligue1",
    leagueLabel: "리그앙",
    team: "AJ 오세르",
    player: "아산 디우세",
    status: "out",
    updated: "2026-08-22",
    headline: "디우세, 전방십자인대 파열… 리그앙 개막 앞두고 장기 이탈",
    summary:
      "세네갈 국가대표 미드필더 아산 디우세가 8월 15일 베르더 브레멘과 치른 프리시즌 마지막 친선경기 도중 왼쪽 무릎을 다쳤어요. 오세르 구단은 8월 20일 정밀 검진 결과 전방십자인대 파열로 확인됐다고 발표했고, 복귀까지 최소 몇 달이 걸릴 전망이에요. 리그앙 개막을 앞두고 중원 운용에 큰 공백이 생기게 됐어요.",
  },
  {
    id: "mlb-yesavage-meniscus",
    photoQuery: "Trey Yesavage",
    teamEn: "Toronto Blue Jays",
    league: "mlb",
    leagueLabel: "MLB",
    team: "토론토 블루제이스",
    player: "트레이 예사베이지",
    status: "out",
    updated: "2026-08-22",
    headline: "예사베이지, 왼쪽 무릎 반월판 수술… 시즌 복귀는 주 단위로 판단",
    summary:
      "블루제이스 선발 트레이 예사베이지가 8월 4일 휴스턴전 등판 도중 무릎 이상을 느껴 교체된 뒤 왼쪽 반월판 수술을 받았어요. 구단은 그를 주 단위로 상태를 지켜보는 중이며, 시즌 아웃을 단정하지는 않고 올해 복귀 가능성도 열어두고 있어요.",
  },
  {
    id: "ligue1-nice-abergel-acl",
    photoQuery: "Laurent Abergel",
    teamEn: "Nice",
    league: "ligue1",
    leagueLabel: "리그앙",
    team: "OGC 니스",
    player: "로랑 아베르갈",
    status: "out",
    updated: "2026-08-22",
    headline: "아베르갈, 전방십자인대 파열로 2027년 봄 복귀 전망",
    summary:
      "니스로 이적한 로랑 아베르갈이 프리시즌 친선경기 도중 오른쪽 무릎을 다쳤고, 정밀 검진 결과 전방십자인대 파열로 확인돼 수술을 받았어요. 구단은 그의 복귀 시점을 2027년 봄으로 예상하고 있어요.",
  },
  {
    id: "laliga-realmadrid-asencio-thigh",
    photoQuery: "Raul Asencio",
    teamEn: "Real Madrid",
    league: "laliga",
    leagueLabel: "라리가",
    team: "레알 마드리드",
    player: "라울 아센시오",
    status: "out",
    updated: "2026-08-22",
    headline: "아센시오, 오른쪽 허벅지 근육 부상… 9월 중순 복귀 전망",
    summary:
      "레알 마드리드 라울 아센시오가 레가네스와의 프리시즌 친선경기에서 전반전을 소화한 뒤 오른쪽 허벅지(대퇴직근) 근육 통증을 느껴 교체됐어요. 정밀 검진 결과 근육 손상이 확인되면서 라리가 개막전인 에스파뇰전에도 결장하게 됐고, 복귀는 9월 중순쯤으로 예상돼요.",
  },
  {
    id: "epl-newcastle-joelinton-livramento",
    photoQuery: "Joelinton",
    teamEn: "Newcastle United",
    league: "epl",
    leagueLabel: "EPL",
    team: "뉴캐슬 유나이티드",
    player: "조엘린턴 · 티노 리브라멘토",
    status: "out",
    updated: "2026-08-22",
    headline: "뉴캐슬, 리버풀전 앞두고 조엘린턴·리브라멘토 결장",
    summary:
      "뉴캐슬이 프리미어리그 개막전인 리버풀전을 앞두고 조엘린턴과 티노 리브라멘토 없이 나서게 됐어요. 조엘린턴은 부상으로 최소 2주가량 결장이 예상돼요.",
  },
  {
    id: "bundesliga-dortmund-can-schlotterbeck",
    photoQuery: "Emre Can",
    teamEn: "Borussia Dortmund",
    league: "bundesliga",
    leagueLabel: "분데스리가",
    team: "보루시아 도르트문트",
    player: "에메레 칸 · 니코 슐로터베크",
    status: "out",
    updated: "2026-08-22",
    headline: "도르트문트, 칸·슐로터베크 동반 결장… 복귀는 각각 12월과 9월 목표",
    summary:
      "에메레 칸이 지난 3월 바이에른전에서 당한 무릎 십자인대 파열로 재활 중이며, 팀은 12월은 되어야 그의 복귀가 가능할 것으로 보고 있어요. 니코 슐로터베크도 월드컵에서 다친 발목 내측인대 부상으로 프리시즌 내내 결장했고, 8월 22일 바이에른과의 슈퍼컵에도 나서지 못한 채 9월 중순 복귀를 목표로 재활하고 있어요.",
  },
  {
    id: "mlb-arenado-intercostal",
    photoQuery: "Nolan Arenado",
    teamEn: "Arizona Diamondbacks",
    league: "mlb",
    leagueLabel: "MLB",
    team: "애리조나 다이아몬드백스",
    player: "놀란 아레나도",
    status: "questionable",
    updated: "2026-08-22",
    headline: "아레나도, 늑간근 경미한 이상 소견… 지명타자로 라인업 복귀",
    summary:
      "왼쪽 옆구리 통증을 호소했던 아레나도가 보스턴에서 받은 MRI 검사에서 늑간근 부위에 경미한 신호만 발견돼 부상자 명단행은 피했어요. 곧바로 레드삭스전 지명타자로 라인업에 복귀했지만, 본인은 전력 송구는 아직 만족스럽지 않다고 밝혀 완전한 수비 복귀까지는 시간이 더 필요해 보여요.",
  },
  {
    id: "mlb-kurtz-thumb",
    photoQuery: "Nick Kurtz",
    teamEn: "Athletics",
    league: "mlb",
    leagueLabel: "MLB",
    team: "오클랜드 애슬레틱스",
    player: "닉 커츠",
    status: "out",
    updated: "2026-08-22",
    headline: "커츠, 오른손 엄지 부상으로 사실상 시즌 아웃",
    summary:
      "신인 커츠가 오른손 엄지 손바닥판 부상으로 8월 4일 혈소판 풍부 혈장(PRP) 주사를 맞고 4주간 보호대를 착용해야 했어요. 9월 초 보호대를 벗을 예정이지만 순위 경쟁에서 멀어진 애슬레틱스가 서두를 이유가 없어 올 시즌 복귀는 어려울 것으로 보여요.",
  },
  {
    id: "mlb-rooker-knee",
    photoQuery: "Brent Rooker",
    teamEn: "Athletics",
    league: "mlb",
    leagueLabel: "MLB",
    team: "오클랜드 애슬레틱스",
    player: "브렌트 루커",
    status: "out",
    updated: "2026-08-22",
    headline: "루커, 왼쪽 무릎 수술로 시즌 아웃",
    summary:
      "지명타자 브렌트 루커가 7월 초 왼쪽 무릎 수술을 받으며 남은 시즌을 모두 접었어요. 애슬레틱스 타선에 또 한 번 공백이 생겼어요.",
  },
  {
    id: "mlb-langeliers-meniscus",
    photoQuery: "Shea Langeliers",
    teamEn: "Athletics",
    league: "mlb",
    leagueLabel: "MLB",
    team: "오클랜드 애슬레틱스",
    player: "셰이 랜젤리어스",
    status: "doubtful",
    updated: "2026-08-22",
    headline: "랜젤리어스, 오른쪽 무릎 반월판 파열… 수술 여부 저울질",
    summary:
      "애슬레틱스 포수 셰이 랜젤리어스가 주루 플레이 도중 오른쪽 무릎 반월판이 파열됐어요. 수술을 받을 경우 회복까지 6~8주가 걸려 9월 초·중순 복귀가 목표가 될 전망이라, 남은 시즌 출전이 불투명해요.",
  },
  {
    id: "bundesliga-mainz-martel-knee",
    photoQuery: "Eric Martel",
    teamEn: "Mainz 05",
    league: "bundesliga",
    leagueLabel: "분데스리가",
    team: "마인츠 05",
    player: "에리크 마르텔",
    status: "out",
    updated: "2026-08-22",
    headline: "마르텔, 무릎 내측 인대 부상으로 시즌 초반 결장",
    summary:
      "쾰른에서 마인츠로 이적한 에리크 마르텔이 두바이 샤바브 알 아흘리와의 연습경기 도중 오른쪽 무릎 내측 인대를 다쳤어요. 정확한 결장 기간은 회복 경과에 따라 정해질 예정이라, 분데스리가 개막을 앞두고 중원 운용에 변수가 생겼어요.",
  },
  {
    id: "mlb-cardinals-pallante-elbow",
    photoQuery: "Andre Pallante",
    teamEn: "St. Louis Cardinals",
    league: "mlb",
    leagueLabel: "MLB",
    team: "세인트루이스 카디널스",
    player: "안드레 팔란테",
    status: "out",
    updated: "2026-08-22",
    headline: "팔란테, 팔꿈치 염증으로 15일 부상자 명단… 매슈스가 로테이션 대체",
    summary:
      "카디널스가 안드레 팔란테를 팔꿈치 염증을 이유로 8월 18일자로 소급 적용된 15일 부상자 명단에 올렸어요. 라이언 페르난데스가 대신 콜업됐고, 팔란테의 로테이션 자리는 퀸 매슈스가 이어받아 이번 주말 선발 등판할 예정이에요.",
  },
  {
    id: "epl-newcastle-miley-schar-elanga-hall",
    photoQuery: "Lewis Miley",
    teamEn: "Newcastle United",
    league: "epl",
    leagueLabel: "EPL",
    team: "뉴캐슬 유나이티드",
    player: "밀리 · 셰어 · 엘랑가 · 홀",
    status: "out",
    updated: "2026-08-22",
    headline: "뉴캐슬, 리버풀전 앞두고 결장자 명단 5명으로 늘어나",
    summary:
      "마티아스 야이슬레 감독이 8월 23일 리버풀과의 개막전을 앞두고 루이스 밀리, 파비안 셰어, 안토니 엘랑가, 루이스 홀까지 부상으로 결장한다고 밝혔어요. 이미 결장이 확정된 조엘린턴까지 더해 뉴캐슬의 결장자는 총 5명으로 늘어났어요.",
  },
  {
    id: "epl-liverpool-ekitike-bradley-leoni-gomez",
    photoQuery: "Hugo Ekitike",
    teamEn: "Liverpool",
    league: "epl",
    leagueLabel: "EPL",
    team: "리버풀",
    player: "에키티케 · 브래들리 · 레오니 · 고메즈",
    status: "out",
    updated: "2026-08-22",
    headline: "리버풀, 개막전 뉴캐슬 원정에 에키티케 등 4명 없이 나서",
    summary:
      "리버풀이 8월 23일 뉴캐슬 원정 개막전에 우고 에키티케, 코너 브래들리, 조반니 레오니, 조 고메즈 없이 나서요. 커티스 존스와 프레디 우드먼도 컨디션에 따라 출전이 불투명한 상태예요.",
  },
  {
    id: "mlb-stanton-calf",
    photoQuery: "Giancarlo Stanton",
    teamEn: "New York Yankees",
    league: "mlb",
    leagueLabel: "MLB",
    team: "뉴욕 양키스",
    player: "지안카를로 스탠턴",
    status: "doubtful",
    updated: "2026-08-22",
    headline: "스탠턴, 재활 중 반대쪽 종아리 부담… 시즌 아웃 가능성 커져",
    summary:
      "오른쪽 종아리 부상에서 재활하던 지안카를로 스탠턴이 이번엔 왼쪽 종아리에 중등도 부담을 입으며 복귀가 다시 불투명해졌어요. 에런 분 감독은 '가능성을 배제하지 않는다'면서도 시즌 잔여 기간 내 복귀를 장담하지는 못했어요.",
  },
  {
    id: "mlb-diaz-neck",
    photoQuery: "Edwin Diaz",
    teamEn: "Los Angeles Dodgers",
    league: "mlb",
    leagueLabel: "MLB",
    team: "로스앤젤레스 다저스",
    player: "에드윈 디아즈",
    status: "out",
    updated: "2026-08-22",
    headline: "디아즈, 목 염증으로 15일 부상자 명단… 마무리 자리 흔들",
    summary:
      "다저스 마무리 에드윈 디아즈가 목 염증으로 15일 부상자 명단에 올랐어요. 팔꿈치 수술 후 복귀한 최근 등판들에서 자책점을 여러 차례 내주며 세이브 기회를 놓치는 등 부진이 이어지던 가운데 나온 조치예요.",
  },
  {
    id: "mlb-arrighetti-return",
    photoQuery: "Spencer Arrighetti",
    teamEn: "Toronto Blue Jays",
    league: "mlb",
    leagueLabel: "MLB",
    team: "토론토 블루제이스",
    player: "스펜서 애리게티",
    status: "ok",
    updated: "2026-08-22",
    headline: "애리게티, 발 부상 딛고 부상자 명단에서 복귀",
    summary:
      "지난달 말부터 발 부상으로 이탈했던 스펜서 애리게티가 8월 21일 15일 부상자 명단에서 활성화됐어요. 트레이드로 블루제이스 유니폼을 입은 뒤 복귀 첫 경기에서는 선발이 아닌 벌크 불펜 역할을 맡을 예정이에요.",
  },
  {
    id: "epl-chelsea-fofana-james-lavia-nkunku",
    photoQuery: "Wesley Fofana",
    teamEn: "Chelsea",
    league: "epl",
    leagueLabel: "EPL",
    team: "첼시",
    player: "포파나 · 제임스 · 라비아 · 은쿤쿠",
    status: "out",
    updated: "2026-08-22",
    headline: "첼시, 개막전 앞두고 포파나·제임스·라비아·은쿤쿠 재활 중",
    summary:
      "첼시가 프리미어리그 개막전인 에버턴전을 앞두고 웨슬리 포파나, 리스 제임스, 로메오 라비아, 크리스토프 은쿤쿠까지 재활 중인 선수들 없이 나서요. 벤 칠웰도 부분 훈련에만 합류한 상태라 이번 경기 출전 여부가 불투명해요.",
  },
  {
    id: "epl-everton-garner-norgaard",
    photoQuery: "James Garner",
    teamEn: "Everton",
    league: "epl",
    leagueLabel: "EPL",
    team: "에버턴",
    player: "가너 · 노르고르",
    status: "out",
    updated: "2026-08-22",
    headline: "에버턴, 가너·노르고르 부상으로 개막전 결장",
    summary:
      "에버턴의 제임스 가너가 지난 7월 서혜부 수술을 받은 뒤 아직 회복하지 못해 개막전에 나서지 못해요. 크리스티안 노르고르도 경미하지만 출전이 어려운 부상을 안고 있어 함께 결장해요.",
  },
  {
    id: "bundesliga-bayern-davies-musiala-return",
    photoQuery: "Alphonso Davies",
    teamEn: "Bayern Munich",
    league: "bundesliga",
    leagueLabel: "분데스리가",
    team: "바이에른 뮌헨",
    player: "다비스 · 무시알라",
    status: "ok",
    updated: "2026-08-22",
    headline: "바이에른, 다비스·무시알라 고강도 재활 훈련 소화… 도르트문트와 슈퍼컵 출전권 확보",
    summary:
      "알폰소 다비스와 자말 무시알라가 재활 책임자 지도 아래 고강도 훈련을 소화하며 도르트문트와의 프란츠 베켄바워 슈퍼컵을 앞두고 출전 가능한 몸 상태를 갖췄어요. 다비스는 근육 부상에서, 무시알라는 월드컵 이후 수술을 거치며 긴 재활을 이어왔어요. 반면 세르지 그나브리와 레나르트 칼은 아직 개인 훈련 단계에 머물러 있어 이번 경기 출전은 불투명해요.",
  },
  {
    id: "epl-manutd-sesko-return",
    photoQuery: "Benjamin Sesko",
    teamEn: "Manchester United",
    league: "epl",
    leagueLabel: "EPL",
    team: "맨체스터 유나이티드",
    player: "베냐민 셰슈코",
    status: "ok",
    updated: "2026-08-22",
    headline: "셰슈코, 정강이 부상 딛고 훈련 복귀… 헐 시티전 명단 포함 전망",
    summary:
      "지난 5월 리버풀전에서 광고판과 충돌해 정강이를 다친 베냐민 셰슈코가 프리시즌 내내 결장한 끝에 이번 주 훈련을 재개했어요. 구단은 무리하게 복귀를 서두르지 않겠다는 입장이지만, 프리미어리그 개막전인 헐 시티 원정 명단에는 이름을 올릴 것으로 보여요.",
  },
  {
    id: "mlb-bluejays-guerrero-concussion",
    photoQuery: "Vladimir Guerrero Jr.",
    teamEn: "Toronto Blue Jays",
    league: "mlb",
    leagueLabel: "MLB",
    team: "토론토 블루제이스",
    player: "블라디미르 게레로 주니어",
    status: "questionable",
    updated: "2026-08-22",
    headline: "게레로 주니어, 뇌진탕 최종 검사 통과… 토요일 양키스전 복귀 전망",
    summary:
      "블루제이스 간판타자 게레로 주니어가 8월 16일 양키스전에서 상대 선수와 충돌해 머리를 다친 뒤 7일 뇌진탕 부상자 명단에 올랐어요. 싱글A 더니든에서 재활 경기를 소화하고 최종 뇌진탕 검사까지 통과하면서, 8월 24일 토요일 뉴욕 원정 양키스전 복귀가 유력해졌어요.",
  },
  {
    id: "laliga-realmadrid-endrick-tchouameni",
    photoQuery: "Endrick",
    teamEn: "Real Madrid",
    league: "laliga",
    leagueLabel: "라리가",
    team: "레알 마드리드",
    player: "엔드릭 · 추아메니",
    status: "out",
    updated: "2026-08-22",
    headline: "레알 마드리드, 엔드릭·추아메니 라리가 개막전 에스파뇰전 결장",
    summary:
      "엔드릭이 경미한 근육 이상을 안고 있어 라리가 개막전인 에스파뇰전 명단에서 빠졌고, 구체적인 복귀 시점도 아직 나오지 않아 다음 경기인 레알 소시에다드전 출전 여부도 불투명해요. 아우렐리앙 추아메니는 허벅지 근육 과부하에서는 회복해 팀 훈련에 합류했지만, 프리시즌 복귀가 늦어 실전 감각이 부족하다는 판단에 따라 이번 경기에는 제외됐어요.",
  },
  {
    id: "bundesliga-mainz-nebel-adductor",
    photoQuery: "Paul Nebel",
    teamEn: "Mainz 05",
    league: "bundesliga",
    leagueLabel: "분데스리가",
    team: "마인츠 05",
    player: "파울 네벨",
    status: "doubtful",
    updated: "2026-08-22",
    headline: "네벨, 사타구니 내전근 부상… 포칼 결장 확정, 개막전도 불투명",
    summary:
      "마인츠 미드필더 파울 네벨이 호프가르텐 전지훈련 마지막 세션에서 슈팅 동작 중 사타구니 통증을 느꼈고, 귀환 후 정밀 검사에서 내전근 부상이 확인됐어요. 8월 23일 DFB-포칼 1라운드 크리쇼전 결장이 확정됐고, 뒤이은 파더보른과의 분데스리가 개막전 출전 여부도 불투명한 상태예요.",
  },
  {
    id: "epl-spurs-kudus-quad",
    photoQuery: "Mohammed Kudus",
    teamEn: "Tottenham",
    league: "epl",
    leagueLabel: "EPL",
    team: "토트넘 홋스퍼",
    player: "모하메드 쿠두스",
    status: "out",
    updated: "2026-08-22",
    headline: "쿠두스, 허벅지 부상 재발 딛고 복귀 임박… 개막전은 결장",
    summary:
      "토트넘 로베르토 데 제르비 감독은 쿠두스의 컨디션이 '거의 준비됐다'고 밝혔지만, 브렌트포드와의 프리미어리그 개막전에는 나서지 못할 전망이에요. 지난 1월 재발한 허벅지 부상으로 지난 시즌 막판 7경기와 월드컵까지 결장했던 만큼, 구단은 복귀를 서두르지 않고 있어요.",
  },
  {
    id: "bundesliga-stuttgart-seimen-diehl",
    photoQuery: "Dennis Seimen",
    teamEn: "VfB Stuttgart",
    league: "bundesliga",
    leagueLabel: "분데스리가",
    team: "VfB 슈투트가르트",
    player: "자이멘 · 딜",
    status: "out",
    updated: "2026-08-22",
    headline: "슈투트가르트, 새 주전 골키퍼 자이멘·딜 나란히 허벅지 부상",
    summary:
      "이번 시즌 주전 골키퍼로 낙점됐던 데니스 자이멘이 훈련 중 허벅지 근육을 다쳐 최소 9월 국가대표 휴식기까지는 결장이 예상돼요. 비슷한 시기 다친 유스틴 딜도 허벅지 근육 손상으로 함께 이탈하면서, 슈투트가르트는 분데스리가 개막 초반을 두 선수 없이 치르게 됐어요.",
  },
  {
    id: "epl-forest-yates-savona",
    photoQuery: "Ryan Yates",
    teamEn: "Nottingham Forest",
    league: "epl",
    leagueLabel: "EPL",
    team: "노팅엄 포레스트",
    player: "예이츠 · 사보나",
    status: "out",
    updated: "2026-08-22",
    headline: "노팅엄 포레스트, 주장 예이츠·사보나 개막전 결장",
    summary:
      "노팅엄 포레스트 주장 라이언 예이츠가 프리시즌 마지막 친선경기부터 결장했고 개막전 복귀도 시간 내에 이루어지지 못했어요. 니콜로 사보나도 함께 결장하며 수비진 운용에 부담이 생겼어요.",
  },
  {
    id: "mlb-yankees-mcmahon-thumb",
    photoQuery: "Ryan McMahon",
    teamEn: "New York Yankees",
    league: "mlb",
    leagueLabel: "MLB",
    team: "뉴욕 양키스",
    player: "라이언 맥마흔",
    status: "out",
    updated: "2026-08-22",
    headline: "맥마흔, 왼손 엄지 2등급 염좌로 10일 부상자 명단",
    summary:
      "라이언 맥마흔이 지난 수요일 오리올스전에서 2루 슬라이딩 도중 왼손 엄지를 다쳤고, 8월 20일자로 소급 적용된 10일 부상자 명단에 올랐어요. 최소 복귀 시점인 8월 30일 전후 활동 재개를 목표로 하고 있어요.",
  },
  {
    id: "epl-arsenal-guimaraes-groin",
    photoQuery: "Bruno Guimaraes",
    teamEn: "Arsenal",
    league: "epl",
    leagueLabel: "EPL",
    team: "아스널",
    player: "브루누 기마랑이스",
    status: "out",
    updated: "2026-08-22",
    headline: "기마랑이스, 데뷔전서 사타구니 부상… 코번트리전 벤치도 제외",
    summary:
      "아스널로 이적한 브루누 기마랑이스가 커뮤니티 실드 데뷔전 전반전을 마친 뒤 사타구니 통증으로 교체됐어요. 아르테타 감독은 경미한 긴장이라고 밝혔지만, 프리시즌 준비 부족까지 겹치며 코번트리 시티와의 리그 개막전 명단에서도 제외됐어요.",
  },
  {
    id: "laliga-espanyol-garcia-puado",
    photoQuery: "Kike Garcia",
    teamEn: "Espanyol",
    league: "laliga",
    leagueLabel: "라리가",
    team: "에스파뇰",
    player: "키케 가르시아 · 하비 푸아도",
    status: "out",
    updated: "2026-08-22",
    headline: "에스파뇰, 레알전 앞두고 키케 가르시아·푸아도 장기 결장",
    summary:
      "에스파뇰이 레알 마드리드와의 개막전을 앞두고 키케 가르시아 없이 나서요. 이달 초 햄스트링을 다친 가르시아는 12월에나 복귀가 가능할 전망이고, 무릎을 다친 하비 푸아도도 최소 11월까지는 그라운드로 돌아오기 어려울 것으로 보여요.",
  },
  {
    id: "mlb-yankees-bellinger-return",
    photoQuery: "Cody Bellinger",
    teamEn: "New York Yankees",
    league: "mlb",
    leagueLabel: "MLB",
    team: "뉴욕 양키스",
    player: "코디 벨린저",
    status: "ok",
    updated: "2026-08-22",
    headline: "벨린저, 햄스트링 부상 딛고 23일 부상자 명단서 복귀",
    summary:
      "왼쪽 햄스트링 긴장으로 이탈했던 코디 벨린저가 8월 22일 직접 다음 날인 23일자로 부상자 명단에서 복귀한다고 밝혔어요. 외야 뎁스에 숨통이 트일 전망이에요.",
  },
  {
    id: "mlb-padres-musgrove-rehab",
    photoQuery: "Joe Musgrove",
    teamEn: "San Diego Padres",
    league: "mlb",
    leagueLabel: "MLB",
    team: "샌디에이고 파드리스",
    player: "조 머스그로브",
    status: "doubtful",
    updated: "2026-08-22",
    headline: "머스그로브, 토미존 재활 순항… 8월 24일 주 4차 재활 등판 예정",
    summary:
      "팔꿈치 토미존 수술에서 회복 중인 조 머스그로브가 곧 불펜 피칭을 소화할 예정이며, 8월 24일이 속한 주에 네 번째 재활 등판을 치를 것으로 보여요. 이후 결과에 따라 1군 콜업 여부가 결정될 전망이에요.",
  },
  {
    id: "mlb-woo-shoulder",
    photoQuery: "Bryan Woo",
    teamEn: "Seattle Mariners",
    league: "mlb",
    leagueLabel: "MLB",
    team: "시애틀 매리너스",
    player: "브라이언 우",
    status: "questionable",
    updated: "2026-08-22",
    headline: "우, 어깨 통증으로 등판 연기… IL행은 피할 듯",
    summary:
      "시애틀 선발 브라이언 우가 지난 등판 도중 어깨 통증을 느껴 8월 22일 예정됐던 다음 선발 등판이 최소 이틀 미뤄졌어요. 구단은 별도 영상 검사 없이 경과를 지켜보고 있고, 댄 윌슨 감독은 부상자 명단행까지는 가지 않을 것으로 낙관하고 있어요.",
  },
  {
    id: "mlb-gimenez-hamstring",
    photoQuery: "Andres Gimenez",
    teamEn: "Toronto Blue Jays",
    league: "mlb",
    leagueLabel: "MLB",
    team: "토론토 블루제이스",
    player: "안드레스 히메네스",
    status: "questionable",
    updated: "2026-08-22",
    headline: "히메네스, 오른쪽 햄스트링 뭉침으로 결장… MRI는 안 받아",
    summary:
      "안드레스 히메네스가 레이스전 1루 주루 도중 오른쪽 햄스트링에 통증을 느껴 교체됐어요. 다음 날 검사에서 근력과 가동 범위 모두 양호해 MRI 없이 데이 투 데이로 분류됐지만, 금요일 라인업에서는 빠졌어요.",
  },
  {
    id: "mlb-frelick-shoulder-return",
    photoQuery: "Sal Frelick",
    teamEn: "Milwaukee Brewers",
    league: "mlb",
    leagueLabel: "MLB",
    team: "밀워키 브루어스",
    player: "살 프렐릭",
    status: "doubtful",
    updated: "2026-08-22",
    headline: "프렐릭, 트리플A 재활 순항… 메이저 복귀 임박",
    summary:
      "어깨 부상으로 이탈했던 살 프렐릭이 트리플A 내슈빌에서 재활 경기를 이어가며 좋은 타격감을 보이고 있어요. 8월 22일 기준 아직 1군에 합류하지 못했지만, 팻 머피 감독은 '조만간 볼 수 있을 것'이라며 복귀가 머지않았음을 시사했어요.",
  },
  {
    id: "mlb-bluejays-smith-hamstring",
    photoQuery: "Josh Smith",
    teamEn: "Toronto Blue Jays",
    league: "mlb",
    leagueLabel: "MLB",
    team: "토론토 블루제이스",
    player: "조시 스미스",
    status: "out",
    updated: "2026-08-22",
    headline: "스미스, 왼쪽 햄스트링 염증으로 10일 부상자 명단",
    summary:
      "조시 스미스가 8월 20일 레이스전 도중 왼쪽 햄스트링에 통증을 느꼈고, 블루제이스는 그를 해당 날짜로 소급 적용된 10일 부상자 명단에 올렸어요. 정확한 손상 정도를 확인하기 위한 MRI 검사가 예정돼 있으며, 빈 자리는 데이비스 슈나이더가 콜업돼 채웠어요.",
  },
  {
    id: "mlb-dodgers-pages-hand-fracture",
    photoQuery: "Andy Pages",
    teamEn: "Los Angeles Dodgers",
    league: "mlb",
    leagueLabel: "MLB",
    team: "로스앤젤레스 다저스",
    player: "앤디 페이지스",
    status: "out",
    updated: "2026-08-22",
    headline: "페이지스, 손등 골절… 4~5주 결장 전망",
    summary:
      "다저스 외야수 앤디 페이지스가 8월 21일 피츠버그전에서 시속 100마일 강속구에 왼손을 맞아 골절 판정을 받았어요. 데이브 로버츠 감독은 대략 4~5주 결장을 예상한다고 밝혔고, 수술 가능성도 열어뒀지만 복귀 시점에는 큰 영향이 없을 것으로 봤어요.",
  },
  {
    id: "epl-crystalpalace-riad-knee",
    photoQuery: "Chadi Riad",
    teamEn: "Crystal Palace",
    league: "epl",
    leagueLabel: "EPL",
    team: "크리스탈 팰리스",
    player: "차디 리아드",
    status: "out",
    updated: "2026-08-23",
    headline: "리아드, 에버턴전서 왼쪽 무릎 부상… 십자인대 손상 우려",
    summary:
      "크리스탈 팰리스 수비수 차디 리아드가 프리미어리그 개막전인 에버턴 원정에서 왼쪽 무릎을 다쳐 눈물을 흘리며 들것에 실려 나갔어요. 십자인대 손상 가능성이 제기되고 있으며, 과거에도 같은 무릎으로 긴 공백을 겪었던 만큼 정밀 검진 결과가 주목돼요.",
  },
  {
    id: "epl-manutd-mount-hamstring",
    photoQuery: "Mason Mount",
    teamEn: "Manchester United",
    league: "epl",
    leagueLabel: "EPL",
    team: "맨체스터 유나이티드",
    player: "메이슨 마운트",
    status: "out",
    updated: "2026-08-23",
    headline: "마운트, PSG와의 프리시즌 친선전서 햄스트링 이상… 국가대표 휴식기까지 결장",
    summary:
      "메이슨 마운트가 PSG와의 프리시즌 친선경기에 선발 출전했다가 18분 만에 햄스트링에 이상을 느껴 잭 플레처와 교체됐어요. 구단은 그의 복귀를 9월 국가대표 휴식기 이후로 내다보고 있어, 첼시 이적 후 반복되던 부상 악재가 다시 발목을 잡는 모습이에요.",
  },
  {
    id: "ligue1-lyon-merah-ankle",
    photoQuery: "Khalis Merah",
    teamEn: "Olympique Lyonnais",
    league: "ligue1",
    leagueLabel: "리그앙",
    team: "올랭피크 리옹",
    player: "칼리스 메라",
    status: "out",
    updated: "2026-08-23",
    headline: "리옹 메라, 훈련 중 충돌로 발목 염좌… 약 한 달 결장",
    summary:
      "19세 미드필더 칼리스 메라가 훈련 중 충돌로 발목을 심하게 접질렸고, 구단은 회복까지 약 한 달을 예상하고 있어요. 이번 결장으로 챔피언스리그 예선 3차전 출전도 어려울 전망이에요.",
  },
  {
    id: "ligue1-angers-mouton-return",
    photoQuery: "Louis Mouton",
    teamEn: "Angers",
    league: "ligue1",
    leagueLabel: "리그앙",
    team: "앙제",
    player: "루이 무통",
    status: "ok",
    updated: "2026-08-23",
    headline: "무통, 반월판 수술 3개월 만에 팀 훈련 복귀",
    summary:
      "왼쪽 무릎 외측 반월판 수술을 받았던 루이 무통이 8월 20일 릴전을 앞두고 앙제 팀 훈련에 복귀했어요. 수술 후 약 3개월 만의 전체 훈련 합류로, 실전 복귀도 머지않았다는 기대가 나오고 있어요.",
  },
];

export const INJURY_LEAGUES = [
  { id: "all", label: "전체" },
  { id: "mlb", label: "MLB" },
  { id: "epl", label: "EPL" },
  { id: "laliga", label: "라리가" },
  { id: "ligue1", label: "리그앙" },
  { id: "bundesliga", label: "분데스리가" },
];
