/* 데일리스코어 부상자 정보 데이터
 * 모든 항목은 구단 공식 발표 및 현지 언론 보도를 확인한 뒤 자체적으로 요약/재작성한 내용입니다.
 * 특정 사이트의 문장을 그대로 옮기지 않고, 확인된 사실(팩트)만 반영해 새로 작성합니다.
 * status: "out"(결장 확정) | "doubtful"(출전 불투명) | "questionable"(출전 여부 미정) | "ok"(복귀/훈련 합류)
 */
export type InjuryStatus = "out" | "doubtful" | "questionable" | "ok";

export interface InjuryItem {
  id: string;
  photoQuery?: string;
  teamEn?: string;
  league: string;
  leagueLabel: string;
  team: string;
  player: string;
  status: InjuryStatus;
  updated: string;
  headline: string;
  summary: string;
}

export const INJURY_STATUS_LABEL: Record<InjuryStatus, string> = {
  out: "결장",
  doubtful: "출전 불투명",
  questionable: "출전 미정",
  ok: "복귀",
};

export const INJURIES: InjuryItem[] = [
  {
    id: "mlb-judge-rib",
    photoQuery: "Aaron Judge",
    teamEn: "New York Yankees",
    league: "mlb",
    leagueLabel: "MLB",
    team: "뉴욕 양키스",
    player: "애런 저지",
    status: "doubtful",
    updated: "2026-08-20",
    headline: "저지, 갈비뼈 피로골절로 재활 중… 이번 주 타격 훈련 돌입",
    summary:
      "갈비뼈 피로골절로 이탈했던 저지가 수영장에서 스윙 관련 재활 훈련을 이어가고 있으며, 8월 17일이 속한 주부터 본격적인 타격 훈련 단계에 들어갈 예정이에요. 실전 복귀까지는 좀 더 시간이 필요할 것으로 보여요.",
  },
  {
    id: "mlb-fried-elbow",
    photoQuery: "Max Fried",
    teamEn: "New York Yankees",
    league: "mlb",
    leagueLabel: "MLB",
    team: "뉴욕 양키스",
    player: "맥스 프리드",
    status: "out",
    updated: "2026-08-17",
    headline: "프리드, 좌완 팔꿈치 골타박상으로 15일 부상자 명단行",
    summary:
      "양키스 선발 프리드가 좌측 팔꿈치 골타박상으로 8월 14일자 소급 적용된 15일 부상자 명단에 올랐어요. 로테이션 복귀 시점은 아직 발표되지 않았어요.",
  },
  {
    id: "mlb-marte-knee",
    photoQuery: "Ketel Marte",
    teamEn: "Arizona Diamondbacks",
    league: "mlb",
    leagueLabel: "MLB",
    team: "애리조나 다이아몬드백스",
    player: "케텔 마르테",
    status: "out",
    updated: "2026-08-20",
    headline: "마르테, 좌측 무릎 염증으로 부상자 명단 등재",
    summary:
      "다이아몬드백스가 8월 20일 밤 케텔 마르테를 좌측 무릎 염증을 이유로 부상자 명단에 올렸어요. 팀 내야진 운용에 변화가 예상돼요.",
  },
  {
    id: "mlb-abrams-ankle",
    photoQuery: "CJ Abrams",
    teamEn: "Washington Nationals",
    league: "mlb",
    leagueLabel: "MLB",
    team: "워싱턴 내셔널스",
    player: "CJ 에이브럼스",
    status: "questionable",
    updated: "2026-08-20",
    headline: "에이브럼스, 발목 염좌로 레인저스전 결장",
    summary:
      "에이브럼스가 8월 19일 경기 막판 발목을 접질렀고, 다음 날 레인저스전에는 결장했어요. 명단 등재 여부는 아직 확정되지 않았어요.",
  },
  {
    id: "mlb-garcia-hamstring",
    photoQuery: "Maikel Garcia",
    teamEn: "Kansas City Royals",
    league: "mlb",
    leagueLabel: "MLB",
    team: "캔자스시티 로열스",
    player: "마이켈 가르시아",
    status: "out",
    updated: "2026-08-20",
    headline: "가르시아, 햄스트링 부상으로 IL 등재 예정",
    summary:
      "쿼트라로 감독이 마이켈 가르시아가 햄스트링 부상으로 부상자 명단에 오를 예정이라고 밝혔어요. 정확한 결장 기간은 추가 검진 후 나올 전망이에요.",
  },
  {
    id: "epl-arsenal-saliba-timber",
    photoQuery: "William Saliba",
    teamEn: "Arsenal",
    league: "epl",
    leagueLabel: "EPL",
    team: "아스널",
    player: "살리바 · 티머버",
    status: "out",
    updated: "2026-08-21",
    headline: "아스널, 개막전서 살리바·티머버 결장",
    summary:
      "아스널이 프리미어리그 개막전을 앞두고 윌리안 살리바와 야프 티머버 없이 나서요. 다만 데클런 라이스와 부카요 사카는 출전 명단에 포함될 예정이에요.",
  },
  {
    id: "epl-mancity-doku",
    photoQuery: "Jeremy Doku",
    teamEn: "Manchester City",
    league: "epl",
    leagueLabel: "EPL",
    team: "맨체스터 시티",
    player: "제레미 도쿠",
    status: "doubtful",
    updated: "2026-08-21",
    headline: "도쿠, 커뮤니티 실드서 종아리 부상… 개막전 결장 위기",
    summary:
      "제레미 도쿠가 커뮤니티 실드 경기 중 종아리를 다쳤어요. 맨시티의 이번 주말 결장 명단에 이름을 올린 유일한 선수예요.",
  },
  {
    id: "epl-manutd-ugarte-deligt",
    photoQuery: "Manuel Ugarte",
    teamEn: "Manchester United",
    league: "epl",
    leagueLabel: "EPL",
    team: "맨체스터 유나이티드",
    player: "우가르테 · 더 리흐트",
    status: "out",
    updated: "2026-08-21",
    headline: "맨유, 우가르테 장기 이탈… 더 리흐트도 컨디션 난조",
    summary:
      "마누엘 우가르테가 무릎 부상으로 장기간 결장이 예상돼요. 마타이스 더 리흐트도 허리 통증으로 아직 출전 가능 상태가 아니에요.",
  },
  {
    id: "epl-spurs-porro-vandeven",
    photoQuery: "Pedro Porro",
    teamEn: "Tottenham",
    league: "epl",
    leagueLabel: "EPL",
    team: "토트넘 홋스퍼",
    player: "포로 · 반 더 벤",
    status: "out",
    updated: "2026-08-21",
    headline: "토트넘, 포로·반 더 벤 결장… 나머지 자원은 정상 가동",
    summary:
      "페드로 포로와 미키 반 더 벤이 이번 경기 명단에서 빠져요. 대신 솔란케, 우도지, 매디슨, 페르난데스는 정상적으로 출전 가능한 상태예요.",
  },
  {
    id: "laliga-realmadrid-rodrygo",
    photoQuery: "Rodrygo",
    teamEn: "Real Madrid",
    league: "laliga",
    leagueLabel: "라리가",
    team: "레알 마드리드",
    player: "호드리구",
    status: "out",
    updated: "2026-08-20",
    headline: "호드리구, 무릎 중상으로 2027년 초 복귀 목표",
    summary:
      "호드리구가 올 시즌 초 심각한 무릎 부상을 당해 2027년 초반이 되어야 그라운드에 복귀할 수 있을 것으로 보여요. 팀은 장기 공백에 대비한 공격진 운용을 준비하고 있어요.",
  },
  {
    id: "laliga-realmadrid-militao-mendy",
    photoQuery: "Eder Militao",
    teamEn: "Real Madrid",
    league: "laliga",
    leagueLabel: "라리가",
    team: "레알 마드리드",
    player: "미리타오 · 멘디",
    status: "out",
    updated: "2026-08-20",
    headline: "레알 마드리드 수비진 연쇄 이탈… 미리타오·멘디 모두 결장",
    summary:
      "에데르 미리타오가 햄스트링 수술 후 최소 한 달가량 결장이 예상되고, 페를랑 멘디도 허벅지 부상으로 상당 기간 빠질 전망이에요. 시즌 초반 수비 로테이션에 부담이 커졌어요.",
  },
  {
    id: "ligue1-monaco-pogba",
    photoQuery: "Paul Pogba",
    teamEn: "Monaco",
    league: "ligue1",
    leagueLabel: "리그앙",
    team: "AS 모나코",
    player: "폴 포그바",
    status: "out",
    updated: "2026-08-21",
    headline: "포그바, 새 허벅지 부상 끝에 모나코와 계약 해지",
    summary:
      "폴 포그바가 훈련 중 왼쪽 허벅지를 다시 다치며 쓰러졌고, 모나코 구단은 결국 그와의 계약을 해지하기로 했어요. 지난 시즌 출전 기회가 극히 적었던 포그바는 이번 부상을 끝으로 클럽을 떠나게 됐어요.",
  },
  {
    id: "ligue1-angers-belkebla",
    photoQuery: "Haris Belkebla",
    teamEn: "Angers",
    league: "ligue1",
    leagueLabel: "리그앙",
    team: "앙제",
    player: "하리스 벨케블라",
    status: "out",
    updated: "2026-08-19",
    headline: "벨케블라, 허벅지 부상 수술… 약 한 달 결장",
    summary:
      "앙제의 하리스 벨케블라가 허벅지 부상으로 수술을 받았고, 회복까지 약 한 달 정도가 소요될 것으로 예상돼요.",
  },
  {
    id: "mlb-soderstrom-hip",
    photoQuery: "Tyler Soderstrom",
    teamEn: "Athletics",
    league: "mlb",
    leagueLabel: "MLB",
    team: "오클랜드 애슬레틱스",
    player: "타일러 소더스트롬",
    status: "out",
    updated: "2026-08-21",
    headline: "소더스트롬, 왼쪽 고관절 수술로 시즌 아웃",
    summary:
      "애슬레틱스 외야수 타일러 소더스트롬이 왼쪽 고관절 임핀지먼트로 결국 시즌을 마감하는 수술을 받기로 했어요. 여름 동안 같은 부위로 두 차례나 부상자 명단에 올랐던 끝에 전문의 상담 후 내려진 결정이에요.",
  },
  {
    id: "mlb-wilson-shoulder",
    photoQuery: "Jacob Wilson",
    teamEn: "Athletics",
    league: "mlb",
    leagueLabel: "MLB",
    team: "오클랜드 애슬레틱스",
    player: "제이컵 윌슨",
    status: "out",
    updated: "2026-08-22",
    headline: "윌슨, 시즌 아웃 공식 확정… 새크라멘토서 전문의 상담",
    summary:
      "애슬레틱스가 제이컵 윌슨의 남은 시즌 결장을 공식 확정했어요. 지난 5월 다이빙 캐치 도중 탈구됐던 왼쪽 어깨가 재활에도 반응하지 않으면서, 윌슨은 새크라멘토로 이동해 전문의 진단을 받을 예정이에요.",
  },
  {
    id: "epl-brighton-minteh",
    photoQuery: "Yankuba Minteh",
    teamEn: "Brighton",
    league: "epl",
    leagueLabel: "EPL",
    team: "브라이튼",
    player: "얀쿠바 민테",
    status: "out",
    updated: "2026-08-21",
    headline: "민테, 다리 수술 받아… 복귀까지 두 달 이상",
    summary:
      "브라이튼의 얀쿠바 민테가 다리 부상으로 수술을 받았고, 복귀까지 두 달 이상 걸릴 것으로 예상돼요. 시즌 개막을 앞두고 팀 공격진에 공백이 생겼어요.",
  },
  {
    id: "epl-brighton-baleba",
    photoQuery: "Carlos Baleba",
    teamEn: "Brighton",
    league: "epl",
    leagueLabel: "EPL",
    team: "브라이튼",
    player: "카를로스 발레바",
    status: "doubtful",
    updated: "2026-08-21",
    headline: "발레바, 발목 인대 부상으로 개막전 결장 위기",
    summary:
      "카를로스 발레바가 발목 인대 부상을 안고 있어 시즌 개막전 출전이 불투명해요. 민테의 이탈까지 겹치며 브라이튼은 개막을 앞두고 전력 손실을 걱정하고 있어요.",
  },
  {
    id: "bundesliga-muslija-acl",
    photoQuery: "Florent Muslija",
    league: "bundesliga",
    leagueLabel: "분데스리가",
    team: "소속팀 확인 중",
    player: "플로렌트 무슬리야",
    status: "out",
    updated: "2026-08-18",
    headline: "무슬리야, 십자인대 부상에서 회복 중… 10월 복귀 목표",
    summary:
      "십자인대 부상으로 이탈했던 무슬리야의 복귀 예상 시점은 10월 10일이에요. 분데스리가 여러 팀에서 8월 하순 복귀를 목표로 하는 선수들도 함께 관찰되고 있어요.",
  },
  {
    id: "epl-astonvilla-gomes-madjo",
    photoQuery: "Joao Gomes",
    teamEn: "Aston Villa",
    league: "epl",
    leagueLabel: "EPL",
    team: "애스턴 빌라",
    player: "조앙 고메스 · 브라이언 마조",
    status: "out",
    updated: "2026-08-21",
    headline: "애스턴 빌라, 고메스·마조 동시 이탈… 개막전 비상",
    summary:
      "울버햄튼에서 이적한 조앙 고메스가 PSG와의 UEFA 슈퍼컵 데뷔전에서 종아리를 다쳐 2~4주가량 결장이 예상돼요. 같은 경기에서 데뷔골을 넣었던 브라이언 마조도 부상을 안고 9월에나 복귀가 가능할 전망이라, 8월 23일 브라이튼전을 앞둔 에메리 감독의 고민이 깊어졌어요.",
  },
  {
    id: "mlb-story-hernia",
    photoQuery: "Trevor Story",
    teamEn: "Boston Red Sox",
    league: "mlb",
    leagueLabel: "MLB",
    team: "보스턴 레드삭스",
    player: "트레버 스토리",
    status: "questionable",
    updated: "2026-08-21",
    headline: "스토리, 서혼 재활 순항 중… 이번 주말 복귀 저울질",
    summary:
      "5월 서혼 수술 후 60일 부상자 명단에 있던 스토리가 트리플A 우스터에서 재활 경기를 이어가고 있어요. 8월 21일 활성화는 불발됐지만 화요일과 수요일 시러큐스 원정 경기를 더 치른 뒤 구단과 최종 재평가를 거쳐 이번 주말 자이언츠전 복귀 여부가 결정될 예정이에요.",
  },
  {
    id: "mlb-chapman-core-surgery",
    photoQuery: "Matt Chapman",
    teamEn: "San Francisco Giants",
    league: "mlb",
    leagueLabel: "MLB",
    team: "샌프란시스코 자이언츠",
    player: "맷 채프먼",
    status: "out",
    updated: "2026-08-22",
    headline: "채프먼, 복부 근육 봉합 수술 받아… 시즌 조기 마감",
    summary:
      "샌프란시스코 3루수 맷 채프먼이 필라델피아에서 복부 코어 근육 봉합 수술을 받으며 남은 시즌을 모두 접었어요. 4월 신시내티 원정 중 다친 부위를 통증을 참고 버티다 7월 1일 부상자 명단에 올랐고, 재활에는 8~12주가 걸릴 전망이라 2027시즌 정상 복귀를 목표로 하고 있어요.",
  },
  {
    id: "mlb-pena-hand-contusion",
    photoQuery: "Jeremy Pena",
    teamEn: "Houston Astros",
    league: "mlb",
    leagueLabel: "MLB",
    team: "휴스턴 애스트로스",
    player: "제레미 페냐",
    status: "questionable",
    updated: "2026-08-22",
    headline: "페냐, 손 타박상 X레이·MRI 모두 이상 없음… 데이 투 데이",
    summary:
      "제레미 페냐가 8월 19일 에인절스전에서 시속 100마일 싱커에 오른손을 맞고 경기 중 교체됐어요. X레이와 MRI 모두 구조적 손상은 없었지만 부기와 통증이 남아 있어 구단은 그를 데이 투 데이로 분류하고 부상자 명단행은 피할 수 있길 기대하고 있어요.",
  },
  {
    id: "ligue1-auxerre-diousse-acl",
    photoQuery: "Assane Dioussé",
    teamEn: "Auxerre",
    league: "ligue1",
    leagueLabel: "리그앙",
    team: "AJ 오세르",
    player: "아산 디우세",
    status: "out",
    updated: "2026-08-22",
    headline: "디우세, 전방십자인대 파열… 리그앙 개막 앞두고 장기 이탈",
    summary:
      "세네갈 국가대표 미드필더 아산 디우세가 8월 15일 베르더 브레멘과 치른 프리시즌 마지막 친선경기 도중 왼쪽 무릎을 다쳤어요. 오세르 구단은 8월 20일 정밀 검진 결과 전방십자인대 파열로 확인됐다고 발표했고, 복귀까지 최소 몇 달이 걸릴 전망이에요. 리그앙 개막을 앞두고 중원 운용에 큰 공백이 생기게 됐어요.",
  },
  {
    id: "mlb-yesavage-meniscus",
    photoQuery: "Trey Yesavage",
    teamEn: "Toronto Blue Jays",
    league: "mlb",
    leagueLabel: "MLB",
    team: "토론토 블루제이스",
    player: "트레이 예사베이지",
    status: "out",
    updated: "2026-08-22",
    headline: "예사베이지, 왼쪽 무릎 반월판 수술… 시즌 복귀는 주 단위로 판단",
    summary:
      "블루제이스 선발 트레이 예사베이지가 8월 4일 휴스턴전 등판 도중 무릎 이상을 느껴 교체된 뒤 왼쪽 반월판 수술을 받았어요. 구단은 그를 주 단위로 상태를 지켜보는 중이며, 시즌 아웃을 단정하지는 않고 올해 복귀 가능성도 열어두고 있어요.",
  },
  {
    id: "ligue1-nice-abergel-acl",
    photoQuery: "Laurent Abergel",
    teamEn: "Nice",
    league: "ligue1",
    leagueLabel: "리그앙",
    team: "OGC 니스",
    player: "로랑 아베르갈",
    status: "out",
    updated: "2026-08-22",
    headline: "아베르갈, 전방십자인대 파열로 2027년 봄 복귀 전망",
    summary:
      "니스로 이적한 로랑 아베르갈이 프리시즌 친선경기 도중 오른쪽 무릎을 다쳤고, 정밀 검진 결과 전방십자인대 파열로 확인돼 수술을 받았어요. 구단은 그의 복귀 시점을 2027년 봄으로 예상하고 있어요.",
  },
  {
    id: "laliga-realmadrid-asencio-thigh",
    photoQuery: "Raul Asencio",
    teamEn: "Real Madrid",
    league: "laliga",
    leagueLabel: "라리가",
    team: "레알 마드리드",
    player: "라울 아센시오",
    status: "out",
    updated: "2026-08-22",
    headline: "아센시오, 오른쪽 허벅지 근육 부상… 9월 중순 복귀 전망",
    summary:
      "레알 마드리드 라울 아센시오가 레가네스와의 프리시즌 친선경기에서 전반전을 소화한 뒤 오른쪽 허벅지(대퇴직근) 근육 통증을 느껴 교체됐어요. 정밀 검진 결과 근육 손상이 확인되면서 라리가 개막전인 에스파뇰전에도 결장하게 됐고, 복귀는 9월 중순쯤으로 예상돼요.",
  },
  {
    id: "epl-newcastle-joelinton-livramento",
    photoQuery: "Joelinton",
    teamEn: "Newcastle United",
    league: "epl",
    leagueLabel: "EPL",
    team: "뉴캐슬 유나이티드",
    player: "조엘린턴 · 티노 리브라멘토",
    status: "out",
    updated: "2026-08-22",
    headline: "뉴캐슬, 리버풀전 앞두고 조엘린턴·리브라멘토 결장",
    summary:
      "뉴캐슬이 프리미어리그 개막전인 리버풀전을 앞두고 조엘린턴과 티노 리브라멘토 없이 나서게 됐어요. 조엘린턴은 부상으로 최소 2주가량 결장이 예상돼요.",
  },
  {
    id: "bundesliga-dortmund-can-schlotterbeck",
    photoQuery: "Emre Can",
    teamEn: "Borussia Dortmund",
    league: "bundesliga",
    leagueLabel: "분데스리가",
    team: "보루시아 도르트문트",
    player: "에메레 칸 · 니코 슐로터베크",
    status: "out",
    updated: "2026-08-22",
    headline: "도르트문트, 칸·슐로터베크 동반 결장… 복귀는 각각 12월과 9월 목표",
    summary:
      "에메레 칸이 지난 3월 바이에른전에서 당한 무릎 십자인대 파열로 재활 중이며, 팀은 12월은 되어야 그의 복귀가 가능할 것으로 보고 있어요. 니코 슐로터베크도 월드컵에서 다친 발목 내측인대 부상으로 프리시즌 내내 결장했고, 8월 22일 바이에른과의 슈퍼컵에도 나서지 못한 채 9월 중순 복귀를 목표로 재활하고 있어요.",
  },
  {
    id: "mlb-arenado-intercostal",
    photoQuery: "Nolan Arenado",
    teamEn: "Arizona Diamondbacks",
    league: "mlb",
    leagueLabel: "MLB",
    team: "애리조나 다이아몬드백스",
    player: "놀란 아레나도",
    status: "questionable",
    updated: "2026-08-22",
    headline: "아레나도, 늑간근 경미한 이상 소견… 지명타자로 라인업 복귀",
    summary:
      "왼쪽 옆구리 통증을 호소했던 아레나도가 보스턴에서 받은 MRI 검사에서 늑간근 부위에 경미한 신호만 발견돼 부상자 명단행은 피했어요. 곧바로 레드삭스전 지명타자로 라인업에 복귀했지만, 본인은 전력 송구는 아직 만족스럽지 않다고 밝혀 완전한 수비 복귀까지는 시간이 더 필요해 보여요.",
  },
  {
    id: "mlb-kurtz-thumb",
    photoQuery: "Nick Kurtz",
    teamEn: "Athletics",
    league: "mlb",
    leagueLabel: "MLB",
    team: "오클랜드 애슬레틱스",
    player: "닉 커츠",
    status: "out",
    updated: "2026-08-22",
    headline: "커츠, 오른손 엄지 부상으로 사실상 시즌 아웃",
    summary:
      "신인 커츠가 오른손 엄지 손바닥판 부상으로 8월 4일 혈소판 풍부 혈장(PRP) 주사를 맞고 4주간 보호대를 착용해야 했어요. 9월 초 보호대를 벗을 예정이지만 순위 경쟁에서 멀어진 애슬레틱스가 서두를 이유가 없어 올 시즌 복귀는 어려울 것으로 보여요.",
  },
  {
    id: "mlb-rooker-knee",
    photoQuery: "Brent Rooker",
    teamEn: "Athletics",
    league: "mlb",
    leagueLabel: "MLB",
    team: "오클랜드 애슬레틱스",
    player: "브렌트 루커",
    status: "out",
    updated: "2026-08-22",
    headline: "루커, 왼쪽 무릎 수술로 시즌 아웃",
    summary:
      "지명타자 브렌트 루커가 7월 초 왼쪽 무릎 수술을 받으며 남은 시즌을 모두 접었어요. 애슬레틱스 타선에 또 한 번 공백이 생겼어요.",
  },
  {
    id: "mlb-langeliers-meniscus",
    photoQuery: "Shea Langeliers",
    teamEn: "Athletics",
    league: "mlb",
    leagueLabel: "MLB",
    team: "오클랜드 애슬레틱스",
    player: "셰이 랜젤리어스",
    status: "doubtful",
    updated: "2026-08-22",
    headline: "랜젤리어스, 오른쪽 무릎 반월판 파열… 수술 여부 저울질",
    summary:
      "애슬레틱스 포수 셰이 랜젤리어스가 주루 플레이 도중 오른쪽 무릎 반월판이 파열됐어요. 수술을 받을 경우 회복까지 6~8주가 걸려 9월 초·중순 복귀가 목표가 될 전망이라, 남은 시즌 출전이 불투명해요.",
  },
  {
    id: "bundesliga-mainz-martel-knee",
    photoQuery: "Eric Martel",
    teamEn: "Mainz 05",
    league: "bundesliga",
    leagueLabel: "분데스리가",
    team: "마인츠 05",
    player: "에리크 마르텔",
    status: "out",
    updated: "2026-08-22",
    headline: "마르텔, 무릎 내측 인대 부상으로 시즌 초반 결장",
    summary:
      "쾰른에서 마인츠로 이적한 에리크 마르텔이 두바이 샤바브 알 아흘리와의 연습경기 도중 오른쪽 무릎 내측 인대를 다쳤어요. 정확한 결장 기간은 회복 경과에 따라 정해질 예정이라, 분데스리가 개막을 앞두고 중원 운용에 변수가 생겼어요.",
  },
  {
    id: "mlb-cardinals-pallante-elbow",
    photoQuery: "Andre Pallante",
    teamEn: "St. Louis Cardinals",
    league: "mlb",
    leagueLabel: "MLB",
    team: "세인트루이스 카디널스",
    player: "안드레 팔란테",
    status: "out",
    updated: "2026-08-22",
    headline: "팔란테, 팔꿈치 염증으로 15일 부상자 명단… 매슈스가 로테이션 대체",
    summary:
      "카디널스가 안드레 팔란테를 팔꿈치 염증을 이유로 8월 18일자로 소급 적용된 15일 부상자 명단에 올렸어요. 라이언 페르난데스가 대신 콜업됐고, 팔란테의 로테이션 자리는 퀸 매슈스가 이어받아 이번 주말 선발 등판할 예정이에요.",
  },
  {
    id: "epl-newcastle-miley-schar-elanga-hall",
    photoQuery: "Lewis Miley",
    teamEn: "Newcastle United",
    league: "epl",
    leagueLabel: "EPL",
    team: "뉴캐슬 유나이티드",
    player: "밀리 · 셰어 · 엘랑가 · 홀",
    status: "out",
    updated: "2026-08-22",
    headline: "뉴캐슬, 리버풀전 앞두고 결장자 명단 5명으로 늘어나",
    summary:
      "마티아스 야이슬레 감독이 8월 23일 리버풀과의 개막전을 앞두고 루이스 밀리, 파비안 셰어, 안토니 엘랑가, 루이스 홀까지 부상으로 결장한다고 밝혔어요. 이미 결장이 확정된 조엘린턴까지 더해 뉴캐슬의 결장자는 총 5명으로 늘어났어요.",
  },
  {
    id: "epl-liverpool-ekitike-bradley-leoni-gomez",
    photoQuery: "Hugo Ekitike",
    teamEn: "Liverpool",
    league: "epl",
    leagueLabel: "EPL",
    team: "리버풀",
    player: "에키티케 · 브래들리 · 레오니 · 고메즈",
    status: "out",
    updated: "2026-08-22",
    headline: "리버풀, 개막전 뉴캐슬 원정에 에키티케 등 4명 없이 나서",
    summary:
      "리버풀이 8월 23일 뉴캐슬 원정 개막전에 우고 에키티케, 코너 브래들리, 조반니 레오니, 조 고메즈 없이 나서요. 커티스 존스와 프레디 우드먼도 컨디션에 따라 출전이 불투명한 상태예요.",
  },
  {
    id: "mlb-stanton-calf",
    photoQuery: "Giancarlo Stanton",
    teamEn: "New York Yankees",
    league: "mlb",
    leagueLabel: "MLB",
    team: "뉴욕 양키스",
    player: "지안카를로 스탠턴",
    status: "doubtful",
    updated: "2026-08-22",
    headline: "스탠턴, 6월 재발 이후 처음으로 주루 훈련 소화… 재활 순항",
    summary:
      "오른쪽 종아리 부상으로 이탈한 지안카를로 스탠턴이 6월 재발 이후 처음으로 양키 스타디움에서 주루 훈련을 소화했어요. 에런 분 감독은 종아리 상태가 계속 좋으면 마이너리그 재활 경기 배정이 다음 단계가 될 수 있다고 밝혔어요.",
  },
  {
    id: "mlb-diaz-neck",
    photoQuery: "Edwin Diaz",
    teamEn: "Los Angeles Dodgers",
    league: "mlb",
    leagueLabel: "MLB",
    team: "로스앤젤레스 다저스",
    player: "에드윈 디아즈",
    status: "out",
    updated: "2026-08-22",
    headline: "디아즈, 목 염증으로 15일 부상자 명단… 마무리 자리 흔들",
    summary:
      "다저스 마무리 에드윈 디아즈가 목 염증으로 15일 부상자 명단에 올랐어요. 팔꿈치 수술 후 복귀한 최근 등판들에서 자책점을 여러 차례 내주며 세이브 기회를 놓치는 등 부진이 이어지던 가운데 나온 조치예요.",
  },
  {
    id: "mlb-arrighetti-return",
    photoQuery: "Spencer Arrighetti",
    teamEn: "Toronto Blue Jays",
    league: "mlb",
    leagueLabel: "MLB",
    team: "토론토 블루제이스",
    player: "스펜서 애리게티",
    status: "ok",
    updated: "2026-08-22",
    headline: "애리게티, 발 부상 딛고 부상자 명단에서 복귀",
    summary:
      "지난달 말부터 발 부상으로 이탈했던 스펜서 애리게티가 8월 21일 15일 부상자 명단에서 활성화됐어요. 트레이드로 블루제이스 유니폼을 입은 뒤 복귀 첫 경기에서는 선발이 아닌 벌크 불펜 역할을 맡을 예정이에요.",
  },
  {
    id: "epl-chelsea-fofana-james-lavia-nkunku",
    photoQuery: "Wesley Fofana",
    teamEn: "Chelsea",
    league: "epl",
    leagueLabel: "EPL",
    team: "첼시",
    player: "포파나 · 제임스 · 라비아 · 은쿤쿠",
    status: "out",
    updated: "2026-08-22",
    headline: "첼시, 개막전 앞두고 포파나·제임스·라비아·은쿤쿠 재활 중",
    summary:
      "첼시가 프리미어리그 개막전인 에버턴전을 앞두고 웨슬리 포파나, 리스 제임스, 로메오 라비아, 크리스토프 은쿤쿠까지 재활 중인 선수들 없이 나서요. 벤 칠웰도 부분 훈련에만 합류한 상태라 이번 경기 출전 여부가 불투명해요.",
  },
  {
    id: "epl-everton-garner-norgaard",
    photoQuery: "James Garner",
    teamEn: "Everton",
    league: "epl",
    leagueLabel: "EPL",
    team: "에버턴",
    player: "가너 · 노르고르",
    status: "out",
    updated: "2026-08-22",
    headline: "에버턴, 가너·노르고르 부상으로 개막전 결장",
    summary:
      "에버턴의 제임스 가너가 지난 7월 서혜부 수술을 받은 뒤 아직 회복하지 못해 개막전에 나서지 못해요. 크리스티안 노르고르도 경미하지만 출전이 어려운 부상을 안고 있어 함께 결장해요.",
  },
  {
    id: "epl-forest-yates-savona",
    photoQuery: "Ryan Yates",
    teamEn: "Nottingham Forest",
    league: "epl",
    leagueLabel: "EPL",
    team: "노팅엄 포레스트",
    player: "예이츠 · 사보나",
    status: "out",
    updated: "2026-08-22",
    headline: "노팅엄 포레스트, 주장 예이츠·사보나 개막전 결장",
    summary:
      "노팅엄 포레스트 주장 라이언 예이츠가 프리시즌 마지막 친선경기부터 결장했고 개막전 복귀도 시간 내에 이루어지지 못했어요. 니콜로 사보나도 함께 결장하며 수비진 운용에 부담이 생겼어요.",
  },
];

export const INJURY_LEAGUES = [
  { id: "all", label: "전체" },
  { id: "mlb", label: "MLB" },
  { id: "epl", label: "EPL" },
  { id: "laliga", label: "라리가" },
  { id: "ligue1", label: "리그앙" },
  { id: "bundesliga", label: "분데스리가" },
];
