/* SportPick 부상자 정보 데이터
 * 모든 항목은 구단 공식 발표 및 현지 언론 보도를 확인한 뒤 자체적으로 요약/재작성한 내용입니다.
 * 특정 사이트의 문장을 그대로 옮기지 않고, 확인된 사실(팩트)만 반영해 새로 작성합니다.
 * status: "out"(결장 확정) | "doubtful"(출전 불투명) | "questionable"(출전 여부 미정) | "ok"(복귀/훈련 합류)
 */
const INJURIES = [
  {
    id: "mlb-judge-rib",
    league: "mlb",
    leagueLabel: "MLB",
    team: "뉴욕 양키스",
    player: "애런 저지",
    status: "doubtful",
    updated: "2026-08-20",
    headline: "저지, 갈비뼈 피로골절로 재활 중… 이번 주 타격 훈련 돌입",
    summary: "갈비뼈 피로골절로 이탈했던 저지가 수영장에서 스윙 관련 재활 훈련을 이어가고 있으며, 8월 17일이 속한 주부터 본격적인 타격 훈련 단계에 들어갈 예정이에요. 실전 복귀까지는 좀 더 시간이 필요할 것으로 보여요.",
  },
  {
    id: "mlb-fried-elbow",
    league: "mlb",
    leagueLabel: "MLB",
    team: "뉴욕 양키스",
    player: "맥스 프리드",
    status: "out",
    updated: "2026-08-17",
    headline: "프리드, 좌완 팔꿈치 골타박상으로 15일 부상자 명단行",
    summary: "양키스 선발 프리드가 좌측 팔꿈치 골타박상으로 8월 14일자 소급 적용된 15일 부상자 명단에 올랐어요. 로테이션 복귀 시점은 아직 발표되지 않았어요.",
  },
  {
    id: "mlb-marte-knee",
    league: "mlb",
    leagueLabel: "MLB",
    team: "애리조나 다이아몬드백스",
    player: "케텔 마르테",
    status: "out",
    updated: "2026-08-20",
    headline: "마르테, 좌측 무릎 염증으로 부상자 명단 등재",
    summary: "다이아몬드백스가 8월 20일 밤 케텔 마르테를 좌측 무릎 염증을 이유로 부상자 명단에 올렸어요. 팀 내야진 운용에 변화가 예상돼요.",
  },
  {
    id: "mlb-abrams-ankle",
    league: "mlb",
    leagueLabel: "MLB",
    team: "워싱턴 내셔널스",
    player: "CJ 에이브럼스",
    status: "questionable",
    updated: "2026-08-20",
    headline: "에이브럼스, 발목 염좌로 레인저스전 결장",
    summary: "에이브럼스가 8월 19일 경기 막판 발목을 접질렀고, 다음 날 레인저스전에는 결장했어요. 명단 등재 여부는 아직 확정되지 않았어요.",
  },
  {
    id: "mlb-garcia-hamstring",
    league: "mlb",
    leagueLabel: "MLB",
    team: "캔자스시티 로열스",
    player: "마이켈 가르시아",
    status: "out",
    updated: "2026-08-20",
    headline: "가르시아, 햄스트링 부상으로 IL 등재 예정",
    summary: "쿼트라로 감독이 마이켈 가르시아가 햄스트링 부상으로 부상자 명단에 오를 예정이라고 밝혔어요. 정확한 결장 기간은 추가 검진 후 나올 전망이에요.",
  },
  {
    id: "epl-arsenal-saliba-timber",
    league: "epl",
    leagueLabel: "EPL",
    team: "아스널",
    player: "살리바 · 티머버",
    status: "out",
    updated: "2026-08-21",
    headline: "아스널, 개막전서 살리바·티머버 결장",
    summary: "아스널이 프리미어리그 개막전을 앞두고 윌리안 살리바와 야프 티머버 없이 나서요. 다만 데클런 라이스와 부카요 사카는 출전 명단에 포함될 예정이에요.",
  },
  {
    id: "epl-mancity-doku",
    league: "epl",
    leagueLabel: "EPL",
    team: "맨체스터 시티",
    player: "제레미 도쿠",
    status: "doubtful",
    updated: "2026-08-21",
    headline: "도쿠, 커뮤니티 실드서 종아리 부상… 개막전 결장 위기",
    summary: "제레미 도쿠가 커뮤니티 실드 경기 중 종아리를 다쳤어요. 맨시티의 이번 주말 결장 명단에 이름을 올린 유일한 선수예요.",
  },
  {
    id: "epl-manutd-ugarte-deligt",
    league: "epl",
    leagueLabel: "EPL",
    team: "맨체스터 유나이티드",
    player: "우가르테 · 더 리흐트",
    status: "out",
    updated: "2026-08-21",
    headline: "맨유, 우가르테 장기 이탈… 더 리흐트도 컨디션 난조",
    summary: "마누엘 우가르테가 무릎 부상으로 장기간 결장이 예상돼요. 마타이스 더 리흐트도 허리 통증으로 아직 출전 가능 상태가 아니에요.",
  },
  {
    id: "epl-spurs-porro-vandeven",
    league: "epl",
    leagueLabel: "EPL",
    team: "토트넘 홋스퍼",
    player: "포로 · 반 더 벤",
    status: "out",
    updated: "2026-08-21",
    headline: "토트넘, 포로·반 더 벤 결장… 나머지 자원은 정상 가동",
    summary: "페드로 포로와 미키 반 더 벤이 이번 경기 명단에서 빠져요. 대신 솔란케, 우도지, 매디슨, 페르난데스는 정상적으로 출전 가능한 상태예요.",
  },
  {
    id: "laliga-realmadrid-rodrygo",
    league: "laliga",
    leagueLabel: "라리가",
    team: "레알 마드리드",
    player: "호드리구",
    status: "out",
    updated: "2026-08-20",
    headline: "호드리구, 무릎 중상으로 2027년 초 복귀 목표",
    summary: "호드리구가 올 시즌 초 심각한 무릎 부상을 당해 2027년 초반이 되어야 그라운드에 복귀할 수 있을 것으로 보여요. 팀은 장기 공백에 대비한 공격진 운용을 준비하고 있어요.",
  },
  {
    id: "laliga-realmadrid-militao-mendy",
    league: "laliga",
    leagueLabel: "라리가",
    team: "레알 마드리드",
    player: "미리타오 · 멘디",
    status: "out",
    updated: "2026-08-20",
    headline: "레알 마드리드 수비진 연쇄 이탈… 미리타오·멘디 모두 결장",
    summary: "에데르 미리타오가 햄스트링 수술 후 최소 한 달가량 결장이 예상되고, 페를랑 멘디도 허벅지 부상으로 상당 기간 빠질 전망이에요. 시즌 초반 수비 로테이션에 부담이 커졌어요.",
  },
  {
    id: "ligue1-monaco-pogba",
    league: "ligue1",
    leagueLabel: "리그앙",
    team: "AS 모나코",
    player: "폴 포그바",
    status: "questionable",
    updated: "2026-08-20",
    headline: "포그바, 왼쪽 허벅지 불편감으로 훈련 소화 못해",
    summary: "폴 포그바가 왼쪽 허벅지에 불편함을 느끼며 훈련을 끝까지 소화하지 못했어요. 다음 경기 출전 여부는 좀 더 지켜봐야 할 것 같아요.",
  },
  {
    id: "ligue1-angers-belkebla",
    league: "ligue1",
    leagueLabel: "리그앙",
    team: "앙제",
    player: "하리스 벨케블라",
    status: "out",
    updated: "2026-08-19",
    headline: "벨케블라, 허벅지 부상 수술… 약 한 달 결장",
    summary: "앙제의 하리스 벨케블라가 허벅지 부상으로 수술을 받았고, 회복까지 약 한 달 정도가 소요될 것으로 예상돼요.",
  },
  {
    id: "bundesliga-muslija-acl",
    league: "bundesliga",
    leagueLabel: "분데스리가",
    team: "소속팀 확인 중",
    player: "플로렌트 무슬리야",
    status: "out",
    updated: "2026-08-18",
    headline: "무슬리야, 십자인대 부상에서 회복 중… 10월 복귀 목표",
    summary: "십자인대 부상으로 이탈했던 무슬리야의 복귀 예상 시점은 10월 10일이에요. 분데스리가 여러 팀에서 8월 하순 복귀를 목표로 하는 선수들도 함께 관찰되고 있어요.",
  },
];
