/**
 * Curated English→Korean team-name translations, used to show Korean team
 * names in the scoreboard. Covers MLB/NBA/NHL, the top-5 European soccer
 * leagues, K League 1/2, and J1 League — the leagues that actually surface
 * in the "인기 리그" sidebar and the TheSportsDB-backed sport tabs.
 *
 * API-FOOTBALL returns thousands of teams across leagues worldwide; a fully
 * accurate translation database for all of them isn't realistic to hand
 * curate, so anything not in this map falls back to its original name
 * rather than risk a wrong translation.
 */
const TEAM_NAME_KO: Record<string, string> = {
  // MLB
  "New York Yankees": "뉴욕 양키스",
  "Boston Red Sox": "보스턴 레드삭스",
  "Toronto Blue Jays": "토론토 블루제이스",
  "Baltimore Orioles": "볼티모어 오리올스",
  "Tampa Bay Rays": "탬파베이 레이스",
  "Chicago White Sox": "시카고 화이트삭스",
  "Cleveland Guardians": "클리블랜드 가디언스",
  "Detroit Tigers": "디트로이트 타이거스",
  "Kansas City Royals": "캔자스시티 로열스",
  "Minnesota Twins": "미네소타 트윈스",
  "Houston Astros": "휴스턴 애스트로스",
  "Los Angeles Angels": "로스앤젤레스 에인절스",
  Athletics: "애슬레틱스",
  "Oakland Athletics": "애슬레틱스",
  "Seattle Mariners": "시애틀 매리너스",
  "Texas Rangers": "텍사스 레인저스",
  "Atlanta Braves": "애틀랜타 브레이브스",
  "Miami Marlins": "마이애미 말린스",
  "New York Mets": "뉴욕 메츠",
  "Philadelphia Phillies": "필라델피아 필리스",
  "Washington Nationals": "워싱턴 내셔널스",
  "Chicago Cubs": "시카고 컵스",
  "Cincinnati Reds": "신시내티 레즈",
  "Milwaukee Brewers": "밀워키 브루어스",
  "Pittsburgh Pirates": "피츠버그 파이리츠",
  "St. Louis Cardinals": "세인트루이스 카디널스",
  "St Louis Cardinals": "세인트루이스 카디널스",
  "Arizona Diamondbacks": "애리조나 다이아몬드백스",
  "Colorado Rockies": "콜로라도 로키스",
  "Los Angeles Dodgers": "로스앤젤레스 다저스",
  "San Diego Padres": "샌디에이고 파드리스",
  "San Francisco Giants": "샌프란시스코 자이언츠",

  // NBA
  "Boston Celtics": "보스턴 셀틱스",
  "Brooklyn Nets": "브루클린 네츠",
  "New York Knicks": "뉴욕 닉스",
  "Philadelphia 76ers": "필라델피아 세븐티식서스",
  "Toronto Raptors": "토론토 랩터스",
  "Chicago Bulls": "시카고 불스",
  "Cleveland Cavaliers": "클리블랜드 캐벌리어스",
  "Detroit Pistons": "디트로이트 피스톤스",
  "Indiana Pacers": "인디애나 페이서스",
  "Milwaukee Bucks": "밀워키 벅스",
  "Atlanta Hawks": "애틀랜타 호크스",
  "Charlotte Hornets": "샬럿 호네츠",
  "Miami Heat": "마이애미 히트",
  "Orlando Magic": "올랜도 매직",
  "Washington Wizards": "워싱턴 위저즈",
  "Denver Nuggets": "덴버 너기츠",
  "Minnesota Timberwolves": "미네소타 팀버울브스",
  "Oklahoma City Thunder": "오클라호마시티 썬더",
  "Portland Trail Blazers": "포틀랜드 트레일블레이저스",
  "Utah Jazz": "유타 재즈",
  "Golden State Warriors": "골든스테이트 워리어스",
  "LA Clippers": "LA 클리퍼스",
  "Los Angeles Clippers": "LA 클리퍼스",
  "Los Angeles Lakers": "로스앤젤레스 레이커스",
  "Phoenix Suns": "피닉스 선즈",
  "Sacramento Kings": "새크라멘토 킹스",
  "Dallas Mavericks": "댈러스 매버릭스",
  "Houston Rockets": "휴스턴 로키츠",
  "Memphis Grizzlies": "멤피스 그리즐리스",
  "New Orleans Pelicans": "뉴올리언스 펠리컨스",
  "San Antonio Spurs": "샌안토니오 스퍼스",

  // NHL
  "Boston Bruins": "보스턴 브루인스",
  "Buffalo Sabres": "버팔로 세이버스",
  "Detroit Red Wings": "디트로이트 레드윙스",
  "Florida Panthers": "플로리다 팬서스",
  "Montreal Canadiens": "몬트리올 캐나디언스",
  "Ottawa Senators": "오타와 세너터스",
  "Tampa Bay Lightning": "탬파베이 라이트닝",
  "Toronto Maple Leafs": "토론토 메이플리프스",
  "Carolina Hurricanes": "캐롤라이나 허리케인스",
  "Columbus Blue Jackets": "콜럼버스 블루재키츠",
  "New Jersey Devils": "뉴저지 데블스",
  "New York Islanders": "뉴욕 아일랜더스",
  "New York Rangers": "뉴욕 레인저스",
  "Philadelphia Flyers": "필라델피아 플라이어스",
  "Pittsburgh Penguins": "피츠버그 펭귄스",
  "Washington Capitals": "워싱턴 캐피털스",
  "Chicago Blackhawks": "시카고 블랙호크스",
  "Colorado Avalanche": "콜로라도 애벌랜치",
  "Dallas Stars": "댈러스 스타스",
  "Minnesota Wild": "미네소타 와일드",
  "Nashville Predators": "내슈빌 프레데터스",
  "St. Louis Blues": "세인트루이스 블루스",
  "St Louis Blues": "세인트루이스 블루스",
  "Utah Hockey Club": "유타 하키 클럽",
  "Utah Mammoth": "유타 매머스",
  "Winnipeg Jets": "위니펙 제츠",
  "Anaheim Ducks": "애너하임 덕스",
  "Calgary Flames": "캘거리 플레임스",
  "Edmonton Oilers": "에드먼턴 오일러스",
  "Los Angeles Kings": "로스앤젤레스 킹스",
  "San Jose Sharks": "새너제이 샤크스",
  "Seattle Kraken": "시애틀 크라켄",
  "Vancouver Canucks": "밴쿠버 커넉스",
  "Vegas Golden Knights": "베가스 골든나이츠",

  // Premier League
  Arsenal: "아스널",
  "Aston Villa": "애스턴 빌라",
  Bournemouth: "본머스",
  Brentford: "브렌트포드",
  Brighton: "브라이튼",
  "Brighton & Hove Albion": "브라이튼",
  Burnley: "번리",
  Chelsea: "첼시",
  "Crystal Palace": "크리스탈 팰리스",
  Everton: "에버턴",
  Fulham: "풀럼",
  Leeds: "리즈 유나이티드",
  "Leeds United": "리즈 유나이티드",
  Leicester: "레스터 시티",
  "Leicester City": "레스터 시티",
  Liverpool: "리버풀",
  Luton: "루턴 타운",
  "Luton Town": "루턴 타운",
  "Manchester City": "맨체스터 시티",
  "Man City": "맨체스터 시티",
  "Manchester United": "맨체스터 유나이티드",
  "Manchester Utd": "맨체스터 유나이티드",
  "Man United": "맨체스터 유나이티드",
  Newcastle: "뉴캐슬 유나이티드",
  "Newcastle United": "뉴캐슬 유나이티드",
  "Nottingham Forest": "노팅엄 포레스트",
  "Sheffield Utd": "셰필드 유나이티드",
  "Sheffield United": "셰필드 유나이티드",
  Southampton: "사우샘프턴",
  Sunderland: "선덜랜드",
  Tottenham: "토트넘 홋스퍼",
  "West Ham": "웨스트햄 유나이티드",
  "West Ham United": "웨스트햄 유나이티드",
  Wolves: "울버햄튼 원더러스",
  Wolverhampton: "울버햄튼 원더러스",
  Ipswich: "입스위치 타운",
  "Ipswich Town": "입스위치 타운",

  // La Liga
  "Real Madrid": "레알 마드리드",
  Barcelona: "바르셀로나",
  "Atletico Madrid": "아틀레티코 마드리드",
  "Atlético Madrid": "아틀레티코 마드리드",
  Sevilla: "세비야",
  "Real Betis": "레알 베티스",
  "Real Sociedad": "레알 소시에다드",
  Villarreal: "비야레알",
  "Athletic Club": "아틀레틱 빌바오",
  "Athletic Bilbao": "아틀레틱 빌바오",
  Valencia: "발렌시아",
  "Celta Vigo": "셀타 비고",
  Osasuna: "오사수나",
  Girona: "지로나",
  Getafe: "헤타페",
  Mallorca: "마요르카",
  "Rayo Vallecano": "라요 바예카노",
  Espanyol: "에스파뇰",
  "Las Palmas": "라스팔마스",
  Alaves: "알라베스",
  "Deportivo Alaves": "알라베스",
  Leganes: "레가네스",
  Valladolid: "바야돌리드",
  "Real Valladolid": "바야돌리드",
  Elche: "엘체",
  Levante: "레반테",

  // Serie A
  Juventus: "유벤투스",
  Inter: "인터 밀란",
  "Internazionale Milano": "인터 밀란",
  "AC Milan": "AC 밀란",
  Milan: "AC 밀란",
  Napoli: "나폴리",
  "AS Roma": "AS 로마",
  Roma: "AS 로마",
  Lazio: "라치오",
  Atalanta: "아탈란타",
  Fiorentina: "피오렌티나",
  Bologna: "볼로냐",
  Torino: "토리노",
  Udinese: "우디네세",
  Sassuolo: "사수올로",
  Genoa: "제노아",
  Cagliari: "칼리아리",
  Verona: "베로나",
  "Hellas Verona": "베로나",
  Empoli: "엠폴리",
  Lecce: "레체",
  Parma: "파르마",
  Como: "코모",
  Venezia: "베네치아",
  Monza: "몬차",
  Cremonese: "크레모네세",
  Pisa: "피사",

  // Bundesliga
  "Bayern Munich": "바이에른 뮌헨",
  "Bayern München": "바이에른 뮌헨",
  "Borussia Dortmund": "보루시아 도르트문트",
  "RB Leipzig": "RB 라이프치히",
  "Bayer Leverkusen": "바이어 레버쿠젠",
  "Union Berlin": "우니온 베를린",
  "Eintracht Frankfurt": "아인트라흐트 프랑크푸르트",
  Wolfsburg: "볼프스부르크",
  "VfL Wolfsburg": "볼프스부르크",
  "Borussia Monchengladbach": "보루시아 묀헨글라트바흐",
  "Borussia M'gladbach": "보루시아 묀헨글라트바흐",
  Freiburg: "프라이부르크",
  "SC Freiburg": "프라이부르크",
  Hoffenheim: "호펜하임",
  Mainz: "마인츠",
  "Mainz 05": "마인츠",
  "FC Koln": "FC 쾰른",
  "1. FC Koln": "FC 쾰른",
  "Werder Bremen": "베르더 브레멘",
  Augsburg: "아우크스부르크",
  Stuttgart: "슈투트가르트",
  "VfB Stuttgart": "슈투트가르트",
  Bochum: "보훔",
  "VfL Bochum": "보훔",
  Heidenheim: "하이덴하임",
  "St Pauli": "FC 상파울리",
  "FC St. Pauli": "FC 상파울리",
  "Hamburger SV": "함부르크 SV",

  // Ligue 1
  "Paris Saint Germain": "파리 생제르맹",
  "Paris Saint-Germain": "파리 생제르맹",
  PSG: "파리 생제르맹",
  Marseille: "올랭피크 마르세유",
  Monaco: "AS 모나코",
  "AS Monaco": "AS 모나코",
  Lyon: "올랭피크 리옹",
  "Olympique Lyonnais": "올랭피크 리옹",
  Lille: "릴 OSC",
  "LOSC Lille": "릴 OSC",
  Nice: "OGC 니스",
  "OGC Nice": "OGC 니스",
  Rennes: "스타드 렌",
  Lens: "RC 랑스",
  "RC Lens": "RC 랑스",
  Strasbourg: "스트라스부르",
  Toulouse: "툴루즈",
  Montpellier: "몽펠리에",
  Nantes: "FC 낭트",
  "FC Nantes": "FC 낭트",
  Reims: "스타드 랭스",
  Brest: "스타드 브레스투아",
  Auxerre: "AJ 오세르",
  "AJ Auxerre": "AJ 오세르",
  Angers: "SCO 앙제",
  "Le Havre": "르아브르",
  Metz: "FC 메스",
  "FC Metz": "FC 메스",
  "Paris FC": "파리 FC",

  // K League 1 & 2
  "Ulsan Hyundai": "울산 HD",
  "Ulsan HD": "울산 HD",
  "Jeonbuk Hyundai Motors": "전북 현대 모터스",
  "Jeonbuk Motors": "전북 현대 모터스",
  "Pohang Steelers": "포항 스틸러스",
  "FC Seoul": "FC 서울",
  "Gwangju FC": "광주 FC",
  "Daegu FC": "대구 FC",
  "Daejeon Citizen": "대전 하나 시티즌",
  "Daejeon Hana Citizen": "대전 하나 시티즌",
  "Gangwon FC": "강원 FC",
  "Suwon FC": "수원 FC",
  "Jeju United": "제주 SK FC",
  "Jeju SK": "제주 SK FC",
  "Gimcheon Sangmu": "김천 상무",
  "FC Anyang": "FC 안양",
  "Bucheon FC 1995": "부천 FC 1995",
  "Cheonan City": "천안 시티",
  "Hwaseong FC": "화성 FC",
  "Ansan Greeners": "안산 그리너스",
  "Seoul E-Land": "서울 이랜드",
  "Gyeongnam FC": "경남 FC",
  "Chungbuk Cheongju": "충북 청주",
  "Incheon United": "인천 유나이티드",
  "Busan IPark": "부산 아이파크",
  "Suwon Samsung Bluewings": "수원 삼성 블루윙즈",
  "Gimhae FC": "김해 FC",
  "Seongnam FC": "성남 FC",

  // J1 League
  "Kashima Antlers": "가시마 앤틀러스",
  "Kawasaki Frontale": "가와사키 프론탈레",
  "Urawa Red Diamonds": "우라와 레드다이아몬즈",
  "Urawa Reds": "우라와 레드다이아몬즈",
  "Yokohama F Marinos": "요코하마 F. 마리노스",
  "Yokohama F. Marinos": "요코하마 F. 마리노스",
  "Vissel Kobe": "비셀 고베",
  "Sanfrecce Hiroshima": "산프레체 히로시마",
  "Gamba Osaka": "감바 오사카",
  "Cerezo Osaka": "세레소 오사카",
  "FC Tokyo": "FC 도쿄",
  "Nagoya Grampus": "나고야 그램퍼스",
  "Avispa Fukuoka": "아비스파 후쿠오카",
  "Kyoto Sanga": "교토 상가",
  "Shonan Bellmare": "쇼난 벨마레",
  "Albirex Niigata": "알비레엑스 니가타",
  "Tokyo Verdy": "도쿄 베르디",
  "Machida Zelvia": "마치다 젤비아",
  "Fagiano Okayama": "파지아노 오카야마",
  "Kashiwa Reysol": "가시와 레이솔",
  "Consadole Sapporo": "콘사돌레 삿포로",
  "Jubilo Iwata": "주빌로 이와타",
};

export function toKoreanTeamName(name: string): string {
  const direct = TEAM_NAME_KO[name];
  if (direct) return direct;

  const trimmed = name.trim();
  const caseInsensitive = Object.keys(TEAM_NAME_KO).find((key) => key.toLowerCase() === trimmed.toLowerCase());
  if (caseInsensitive) return TEAM_NAME_KO[caseInsensitive];

  return name;
}
